import { roundServer } from './server-clock';
import { test,expect,type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';
import { create,join,start,peek,turn,nextActor,clean,state } from './helpers';

test('four full rounds, automatic initial peeks, scoring, reconnect, and a fresh game',async({browser,page})=>{
 const clock=await roundServer();try{
 mkdirSync('artifacts',{recursive:true});const link=await create(page,clock.url);const guest=await join(browser,link,'Bea');const pages=[page,guest];await expect(page.locator('[data-slot]')).toHaveCount(0);await expect(page.locator('.lobby-players li')).toHaveCount(2);await page.screenshot({path:'artifacts/ready-lobby.png'});await start(pages,()=>clock.finish(pages));
 for(let round=1;round<=4;round++){
  await expect(page.locator('.round-label')).toHaveText(`Round ${round} / 4`);await peek(pages);
  if(round===1){await expect.poll(()=>Date.now()>=state(page).visualUntil).toBe(true);await expect(page.locator('.flying-card')).toHaveCount(0);await page.screenshot({path:'artifacts/table-2-desktop.png'});await page.setViewportSize({width:820,height:1180});await page.screenshot({path:'artifacts/table-2-tablet.png'});await page.setViewportSize({width:1440,height:1000});}
  if(round===2){await guest.reload();await expect.poll(()=>state(guest)?.players.every(p=>p.connected)).toBe(true);await expect.poll(()=>state(page).paused).toBeUndefined();}
  const caller=await turn(pages);await expect(caller.getByRole('button',{name:'ARCHDUKE!',exact:true})).toBeEnabled();expect(state(caller).canCallArchduke).toBe(true);await caller.getByRole('button',{name:'ARCHDUKE!',exact:true}).click();await turn(pages);const countdown=caller.locator('.archduke-button[aria-label^="Final matching countdown"]');await expect(countdown).toBeVisible();if(round===1){await expect(caller.locator('.flying-card')).toHaveCount(0);await expect(countdown).toHaveText('3');await expect(caller.locator('[data-endpoint=discard] .card-front img')).toBeVisible();await caller.screenshot({path:'artifacts/final-countdown.png'});}await expect(caller.getByRole('button',{name:'Finish round',exact:true})).toHaveCount(0);
  for(const p of pages){await expect(p.locator('.game')).toHaveAttribute('data-phase',round===4?'GAME_RESULTS':'ROUND_RESULTS',{timeout:10000});await expect(p.getByRole('dialog')).toHaveCount(0);await expect(p.locator('.seat .card-front img')).not.toHaveCount(0);}
  if(round===1){await expect(page.getByRole('button',{name:'Next',exact:true})).toBeVisible();await page.reload();await expect(page.locator('.game')).toHaveAttribute('data-phase','ROUND_RESULTS');await expect(page.getByRole('dialog')).toHaveCount(0);}
  for(const p of pages){await p.getByRole('button',{name:'Next',exact:true}).click();await expect(p.getByRole('dialog')).toBeVisible();await expect(p.locator('.podium-entry')).toHaveCount(2);await expect(p.locator('.podium-totals')).toHaveCount(2);}
  if(round===4){await page.screenshot({path:'artifacts/final-results.png'});await expect(page.getByRole('heading',{name:'Final Scores',exact:true})).toBeVisible();}
  if(round===4){await page.getByRole('button',{name:'New Game',exact:true}).click();for(const p of pages){await expect(p.locator('.room-lobby')).toBeVisible();await expect(p.getByRole('button',{name:'Ready',exact:true})).toBeEnabled();await expect(p.locator('.room-lobby')).toHaveCSS('background-color','rgb(203, 215, 229)');}}
  else{for(const p of pages){await p.getByRole('button',{name:'Next',exact:true}).click();await expect(p.locator('.seat.own').getByRole('button',{name:'Ready',exact:true})).toBeVisible();await expect(p.locator('.game')).toHaveCSS('background-color','rgb(203, 215, 229)');}await expect(page.locator('.game')).toHaveAttribute('data-phase','LOBBY');}
  await page.screenshot({path:'artifacts/round-ready.png'});await start(pages,()=>clock.finish(pages));

 }
 await expect(page.locator('.round-label')).toHaveText('Round 1 / 4');clean(pages);await guest.context().close();
 }finally{await clock.close();}
});

test('direct Give, Swap, Peek, stable base holes, private draw motion, and expanded hands',async({browser,page})=>{
 const link=await create(page,'http://localhost:3101');const guest=await join(browser,link,'Bea');const pages=[page,guest];await start(pages);await peek(pages);const originalHand=await page.locator('.seat.own .card-grid').boundingBox();const originalCard=await page.locator('.seat.own [data-slot="0"]').boundingBox();
 const slot=(p:Page,own:boolean,n:number)=>p.locator(`.seat${own?'.own':':not(.own)'} [data-slot="${n}"]`);
 const moving=slot(guest,true,2),before=await moving.boundingBox(),bottom=await slot(guest,true,3).boundingBox();const revision=state(guest).players.find(p=>p.id===state(guest).you)!.slots[2].rev;await slot(guest,true,0).click();await expect(slot(guest,true,0)).toHaveClass(/hole/);await expect(moving).toHaveAttribute('data-column','1');await guest.screenshot({path:'artifacts/stable-base-hole.png'});expect((await moving.boundingBox())!.x).toBe(before!.x);expect((await slot(guest,true,3).boundingBox())!.x).toBe(bottom!.x);expect(state(guest).players.find(p=>p.id===state(guest).you)!.slots[2].rev).toBe(revision);await expect(slot(guest,true,0)).toHaveClass(/hole/);await turn(pages,0);
 await page.getByRole('button',{name:'Give to Bea'}).click();await expect(guest.locator('.seat.own [data-slot]')).toHaveCount(5);await expect(slot(guest,true,0)).toHaveClass(/hole/);await expect(slot(guest,true,4)).toHaveAttribute('data-row','0');await expect(slot(guest,true,4)).toHaveAttribute('data-column','0');await expect(guest.locator('.seat.own .card-front img')).toHaveCount(0);
 await turn(pages);await turn(pages,1);await slot(page,true,0).click();await slot(page,false,1).click();await expect(page.locator('.flying-card[data-motion="swap"]')).toHaveCount(2);await page.screenshot({path:'artifacts/swap-mid-motion.png'});await expect(page.locator('.flying-card[data-motion="swap"]')).toHaveCount(0);await expect(page.locator('.seat .card-front img')).toHaveCount(0);
 await turn(pages);await turn(pages,2);await slot(page,false,2).click();await expect(page.locator('.opponent-peek-card .card-front img')).toHaveAttribute('alt','Card 3');await expect(page.locator('.opponent-peek-card')).toHaveAttribute('data-phase','open');await expect(slot(guest,true,2).locator('.card-front img')).toHaveCount(0);await page.screenshot({path:'artifacts/private-peek.png'});await page.locator('.opponent-peek-card').click();await expect(page.locator('.opponent-peek-card')).toHaveCount(0);await expect(slot(page,false,2).locator('.card-front img')).toHaveCount(0);

 // Two known wrong cards in one intentional batch each add an unknown card.
 const guestCount=await guest.locator('.seat.own [data-slot]').count();await slot(guest,true,2).click();await slot(guest,true,3).click();await expect(guest.locator('.invalid-penalty-flight')).toHaveCount(1);await guest.screenshot({path:'artifacts/batch-penalty-mid.png'});await expect(guest.locator('.seat.own [data-slot]')).toHaveCount(guestCount+2);for(const row of [0,1])await expect(guest.locator(`.seat.own [data-row="${row}"]:not(.hole)`)).toHaveCount(3);await expect(guest.locator('.flying-card')).toHaveCount(0);for(const p of pages){const recipient=state(p).players.find(q=>q.id===state(guest).you)!;expect(recipient.slots.slice(guestCount).every(s=>s.value===undefined)).toBe(true);}await page.screenshot({path:'artifacts/opponent-expanded-centered.png'});

 for(let i=0;i<9;i++){const actor=await nextActor(pages);await actor.getByRole('button',{name:'Draw from draw pile',exact:true}).click();const pending=actor.locator('.seat.own .pending-card');await expect(pending).toBeEnabled();const value=state(actor).held?.value;await actor.locator('[data-endpoint="discard"]').click();await expect.poll(()=>state(actor).held).toBeUndefined();if(value!==7){await slot(page,true,3).evaluate(element=>(element as HTMLButtonElement).click());const count=await page.locator('.seat.own [data-slot]').count();if([6,8].includes(count)){expect((await page.locator('.seat.own .card-grid').boundingBox())!.width).toBeCloseTo(originalHand!.width*1.3,0);expect((await page.locator('.seat.own [data-slot="0"]').boundingBox())!.width).toBe(originalCard!.width);await page.screenshot({path:`artifacts/overlap-${count}-cards.png`});}}}
 await expect.poll(()=>page.locator('.seat.own [data-slot]').count()).toBeGreaterThanOrEqual(10);expect((await page.locator('.seat.own .card-grid').boundingBox())!.width).toBeCloseTo(originalHand!.width*1.3,0);expect((await page.locator('.seat.own [data-slot="0"]').boundingBox())!.width).toBe(originalCard!.width);await expect(page.locator('.grid-tools')).toHaveCount(0);
 await page.setViewportSize({width:820,height:1180});await expect(page.locator('.game')).not.toHaveClass(/resizing/);for(const card of await page.locator('.seat.own [data-slot]').all())await expect(card).toBeInViewport({ratio:.75});const lastCard=page.locator('.seat.own [data-slot]').last();await lastCard.focus();await expect(lastCard).toBeFocused();await expect(lastCard.locator('.card-front img')).toHaveCount(0);await page.screenshot({path:'artifacts/dense-hand-focus.png'});await expect(lastCard).toBeInViewport({ratio:.75});await page.screenshot({path:'artifacts/expanded-hand-portrait.png'});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(820);clean(pages);await guest.context().close();
});

test('memory process restart shows terminal room loss',async({browser,page})=>{
 const {spawn}=await import('node:child_process');const url='http://localhost:3200';let child:ReturnType<typeof spawn>|undefined;let guest:Page|undefined;
 async function launch(){child=spawn(process.execPath,['dist/server/server/main.js'],{env:{...process.env,NODE_ENV:'test',PORT:'3200',PUBLIC_ORIGIN:url,PERSISTENCE:'memory'},stdio:['ignore','pipe','pipe']});const current=child;await new Promise<void>((r,j)=>{current.stdout!.on('data',data=>{if(String(data).includes('Archduke listening'))r();});current.once('exit',code=>j(new Error(`Server exited ${code}`)));});}
 async function stop(){if(!child)return;const current=child;const exited=new Promise<void>(r=>current.once('exit',()=>r()));current.kill('SIGKILL');await exited;child=undefined;}
 try{await launch();const link=await create(page,url);guest=await join(browser,link,'Bea');await start([page,guest]);await peek([page,guest]);await stop();await launch();await page.reload();await expect(page.getByRole('heading',{name:'This game is no longer available'})).toBeVisible();}finally{if(guest)await guest.context().close();await stop();}
});

test('lost creation acknowledgement survives refresh and retries the same admission',async({page})=>{
 let createdRoom='';const ids:string[]=[];await page.route('**/api/create',async route=>{ids.push(route.request().postDataJSON().id);const response=await route.fetch();createdRoom=(await response.json()).room;await route.abort('failed');},{times:1});
 await page.goto('/');await page.getByRole('textbox',{name:'Name',exact:true}).fill('Retry host');await page.getByRole('button',{name:'Start',exact:true}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();page.on('request',r=>{if(r.url().endsWith('/api/create'))ids.push(r.postDataJSON().id);});await page.getByRole('textbox',{name:'Name',exact:true}).fill('Retry host');await page.getByRole('button',{name:'Start',exact:true}).click();await expect(page).toHaveURL(new RegExp(`/room/${createdRoom}$`));expect(ids[1]).toBe(ids[0]);await expect(page.locator('.lobby-players li')).toHaveCount(1);
});
