import { test, expect, type Browser, type Page } from '@playwright/test';
import { mkdirSync } from 'node:fs';
const secret='browser-test-passphrase';
const observed=new WeakMap<Page,string[]>();
function observe(page:Page){if(!observed.has(page)){const list:string[]=[];observed.set(page,list);errors(page,list);}}
function clean(pages:Page[]){for(const page of pages)expect(observed.get(page)??[]).toEqual([]);}
async function create(page:Page,url='http://localhost:3100'){observe(page);await page.goto(url);await page.getByLabel('Your display name').fill('Ada');await page.getByLabel('Host passphrase').fill(secret);await page.getByRole('button',{name:'Create a private table'}).click();await expect(page.getByRole('heading',{name:'Make yourself at home.'})).toBeVisible();return (await page.locator('.table-toolbar strong').innerText()).trim();}
async function join(browser:Browser,code:string,name:string,url='http://localhost:3100'){const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();observe(page);await page.goto(url);await page.getByRole('button',{name:'Join game',exact:true}).click();await page.getByLabel('Your display name').fill(name);await page.getByLabel('Invitation link or room code').fill(code);await page.getByRole('button',{name:'Join your friends'}).click();await expect(page.getByRole('heading',{name:'Make yourself at home.'})).toBeVisible();return page;}
async function start(pages:Page[]){for(const p of pages)await p.getByRole('button',{name:'Ready to play',exact:true}).click();await pages[0].getByRole('button',{name:'Start game',exact:true}).click();}
async function peek(pages:Page[]){for(const p of pages){const own=p.locator('.seats .seat.own');await expect(own.locator('[data-slot="0"]')).toBeEnabled();await own.locator('[data-slot="0"]').focus();await own.locator('[data-slot="0"]').press('Enter');await own.locator('[data-slot="1"]').click();await p.getByRole('button',{name:'Peek at selected two'}).click();await expect(own.locator('img:not([alt="Face-down card"])')).toHaveCount(2);await expect(p.locator('.seats .seat:not(.own) img:not([alt="Face-down card"])')).toHaveCount(0);await p.getByRole('button',{name:'Hide cards & ready'}).click();await expect(own.locator('img:not([alt="Face-down card"])')).toHaveCount(0);}}
async function nextActor(pages:Page[]){let actor:Page|undefined;await expect.poll(async()=>{for(const p of pages)if(await p.getByRole('button',{name:'Draw from draw pile',exact:true}).isEnabled()){actor=p;return true;}return false;},{timeout:15000}).toBe(true);return actor!;}
async function turn(pages:Page[],slot?:number){const p=await nextActor(pages);await p.getByRole('button',{name:'Draw from draw pile',exact:true}).click();if(slot===undefined)await p.getByRole('button',{name:'Discard drawn card',exact:true}).click();else{await expect(p.getByText('Choose an occupied own slot to replace',{exact:false})).toBeVisible();await expect.poll(()=>p.locator('.notice').filter({hasText:'Wait for the draw'}).count()).toBe(0); // movement authority remains on server
 await expect(p.getByRole('button',{name:'Discard drawn card',exact:true})).toBeEnabled();await p.locator(`.seats .seat.own [data-slot="${slot}"]`).click();}return p;}
function errors(p:Page,list:string[]){p.on('pageerror',e=>list.push(e.message));p.on('console',m=>{if(m.type()==='error')list.push(m.text());});}

test('four full rounds, scoring, reconnect, and a fresh game through UI controls',async({browser,page})=>{
 mkdirSync('artifacts',{recursive:true});const errs:string[]=[];errors(page,errs);await page.goto('/');await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true});const code=await create(page);const guest=await join(browser,code,'Bea');errors(guest,errs);const pages=[page,guest];await start(pages);
 for(let round=1;round<=4;round++){
  await expect(page.locator('.round-label')).toContainText(`ROUND ${round} / 4`);await peek(pages);
  if(round===1){await page.screenshot({path:'artifacts/table-2-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/table-2-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});}
  if(round===2){await guest.reload();await expect(page.getByRole('heading',{name:'Table paused'})).toBeVisible();await expect(guest.getByText('Connected ·',{exact:false})).toBeVisible();await page.getByRole('button',{name:'Resume game'}).click();}
  const caller=await turn(pages);await caller.getByRole('button',{name:'Call Archduke',exact:true}).click();await turn(pages);await caller.getByRole('button',{name:'Finish round',exact:true}).click();
  for(const p of pages){await expect(p.getByRole('dialog')).toContainText('got dead last!');await p.getByRole('button',{name:'View standings'}).click();await expect(p.locator('.results tbody tr')).toHaveCount(2);await expect(p.locator('.results thead')).toContainText(`R${round} place`);}
  if(round===4){await page.screenshot({path:'artifacts/final-results.png',fullPage:true});await expect(page.getByRole('heading',{name:'Final standings'})).toBeVisible();}
  for(const p of pages)await p.getByRole('button',{name:round===4?'Ready for a new game':'Ready for next round',exact:true}).click();
  await page.getByRole('button',{name:round===4?'Start new game':'Start next round',exact:true}).click();
 }
 await expect(page.locator('.round-label')).toContainText('ROUND 1 / 4');expect(errs).toEqual([]);await guest.context().close();
});

test('six and ten seats remain targetable, with desktop and mobile screenshots',async({browser,page})=>{
 const code=await create(page);const pages=[page];for(let i=1;i<10;i++)pages.push(await join(browser,code,`Friend ${i+1}`));await start(pages);await expect(page.locator('.seats .seat.own [data-slot="0"]')).toBeEnabled();await expect(page.locator('.flying-card')).toHaveCount(0);await expect(page.locator('.seats .seat')).toHaveCount(10);await page.screenshot({path:'artifacts/table-10-desktop.png',fullPage:true});
 for(const seat of await page.locator('.seats .seat').all()){const box=await seat.boundingBox();expect(box!.x).toBeGreaterThanOrEqual(0);expect(box!.x+box!.width).toBeLessThanOrEqual(1440);expect(box!.y+box!.height).toBeLessThanOrEqual(1000);}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/table-10-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);await page.locator('.seats .seat').last().getByRole('button',{name:'Focus grid'}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.screenshot({path:'artifacts/mobile-focus.png',fullPage:true});await page.getByRole('button',{name:'Close dialog'}).click();clean(pages);for(const p of pages.slice(1))await p.context().close();
 const sixContext=await browser.newContext({viewport:{width:1440,height:1000}});const six=await sixContext.newPage();const sixCode=await create(six);const sixPages=[six];for(let i=1;i<6;i++)sixPages.push(await join(browser,sixCode,`Six ${i+1}`));await start(sixPages);await expect(six.locator('.seats .seat.own [data-slot="0"]')).toBeEnabled();await expect(six.locator('.flying-card')).toHaveCount(0);await six.screenshot({path:'artifacts/table-6-desktop.png',fullPage:true});await six.setViewportSize({width:390,height:844});await six.screenshot({path:'artifacts/table-6-mobile.png',fullPage:true});clean(sixPages);for(const p of sixPages)await p.context().close();
});

test('special Give, Swap, Peek and matching with a test-only injected shuffle',async({browser,page})=>{
 const url='http://localhost:3101';const errs:string[]=[];errors(page,errs);const code=await create(page,url);const guest=await join(browser,code,'Bea',url);errors(guest,errs);const pages=[page,guest];await start(pages);await peek(pages);
 await guest.locator('.seats .seat.own [data-slot="0"]').click();await expect(guest.locator('.seats .seat.own [data-slot="0"]')).toHaveClass(/hole/);
 const beforeGive=await guest.locator('.seats .seat.own [data-slot="2"]').boundingBox();expect(await turn(pages,0)).toBe(page);await page.getByRole('button',{name:'Give to Bea',exact:true}).click();await expect(page.locator('.seats .seat:not(.own) .card')).toHaveCount(5);const afterGive=await guest.locator('.seats .seat.own [data-slot="2"]').boundingBox();expect(afterGive!.x).toBe(beforeGive!.x);expect(afterGive!.y).toBe(beforeGive!.y);await expect(page.locator('.seats .seat:not(.own) img:not([alt="Face-down card"])')).toHaveCount(0);
 await turn(pages);await turn(pages,1);await page.locator('.seats .seat.own [data-slot="0"]').click();await page.locator('.seats .seat:not(.own) [data-slot="1"]').click();await page.getByRole('button',{name:'Confirm swap'}).click();await expect(page.getByText('Ada swapped the selected cards.',{exact:true}).first()).toBeVisible();await page.screenshot({path:'artifacts/swap-table.png',fullPage:true});
 await turn(pages);await turn(pages,2);await page.locator('.seats .seat:not(.own) [data-slot="2"]').click();await page.getByRole('button',{name:'Confirm peek'}).click();await expect(page.locator('.seats .seat:not(.own) [data-slot="2"] img')).toHaveAttribute('alt','Card 3');await expect(guest.locator('.seats .seat.own [data-slot="2"] img')).toHaveAttribute('alt','Face-down card');await page.screenshot({path:'artifacts/private-peek.png',fullPage:true});await page.getByRole('button',{name:'Done peeking'}).click();await expect(page.locator('.seats .seat:not(.own) [data-slot="2"] img')).toHaveAttribute('alt','Face-down card');// Grow an actual hand through wrong matches in fresh windows; slot 4 is still known to be 7 in this fixture.
 const fixed=await page.locator('.seats .seat.own [data-slot="3"]').boundingBox();
 for(let i=0;i<14;i++){const actor=await nextActor(pages);await actor.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await expect(actor.getByRole('button',{name:'Discard drawn card'})).toBeEnabled();const drawn=await actor.locator('.held img').getAttribute('alt');await actor.getByRole('button',{name:'Discard drawn card'}).click();if(drawn!=='Card 7'){await page.locator('.seats .seat.own [data-slot="3"]').click();await expect(page.getByRole('alert')).toContainText('Incorrect match');await page.getByRole('button',{name:'Dismiss message'}).click();}}
 expect(await page.locator('.seats .seat.own .card').count()).toBeGreaterThanOrEqual(12);
 const grown=await page.locator('.seats .seat.own [data-slot="3"]').boundingBox();expect(grown!.x).toBe(fixed!.x);expect(grown!.y).toBe(fixed!.y);
 await expect(page.locator('.seats .seat.own [data-slot="3"] img')).toHaveAttribute('alt','Face-down card');await page.screenshot({path:'artifacts/large-hand-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.locator('.seats .seat.own').getByRole('button',{name:'Focus grid'}).click();await page.getByRole('dialog').getByRole('button',{name:'Next columns for Ada'}).click();await page.getByRole('dialog').locator('[data-slot]').last().focus();await expect(page.getByRole('dialog').locator('[data-slot]').last()).toBeInViewport();await page.screenshot({path:'artifacts/large-hand-mobile.png',fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390);
 expect(errs).toEqual([]);await guest.context().close();
});

test('memory process restart shows terminal room loss in the actual browser',async({browser,page})=>{
 const {spawn}=await import('node:child_process');const url='http://localhost:3200';let child:ReturnType<typeof spawn>|undefined;let guest:Page|undefined;
 async function launch(){child=spawn(process.execPath,['dist/server/server/main.js'],{env:{...process.env,NODE_ENV:'test',PORT:'3200',PUBLIC_ORIGIN:url,HOST_SECRET:secret,PERSISTENCE:'memory'},stdio:['ignore','pipe','pipe']});const processChild=child;await new Promise<void>((r,j)=>{processChild.stdout!.on('data',data=>{if(String(data).includes('Archduke listening'))r();});processChild.once('exit',code=>j(new Error(`Test server exited ${code}`)));});}
 async function stop(){if(!child)return;const processChild=child;const exited=new Promise<void>(r=>processChild.once('exit',()=>r()));processChild.kill('SIGKILL');await exited;child=undefined;}
 try{await launch();const code=await create(page,url);guest=await join(browser,code,'Bea',url);await start([page,guest]);await peek([page,guest]);await stop();await launch();await page.reload();await expect(page.getByRole('heading',{name:'This game is no longer available'})).toBeVisible();await expect(page.getByRole('link',{name:'Back to home'})).toBeVisible();await page.screenshot({path:'artifacts/memory-restart-room-loss.png',fullPage:true});}finally{if(guest)await guest.context().close();await stop();}
});

test('lost creation acknowledgement survives refresh and retries the same admission',async({page})=>{
 let createdRoom='';const ids:string[]=[];await page.route('**/api/create',async route=>{ids.push(route.request().postDataJSON().id as string);const response=await route.fetch();createdRoom=(await response.json()).room;await route.abort('failed');},{times:1});
 await page.goto('/');await page.getByLabel('Your display name').fill('Retry host');await page.getByLabel('Host passphrase').fill(secret);await page.getByRole('button',{name:'Create a private table'}).click();await expect(page.getByRole('alert')).toBeVisible();await page.reload();page.on('request',request=>{if(request.url().endsWith('/api/create'))ids.push(request.postDataJSON().id as string);});await page.getByLabel('Your display name').fill('Retry host');await page.getByLabel('Host passphrase').fill(secret);await page.getByRole('button',{name:'Create a private table'}).click();await expect(page).toHaveURL(new RegExp(`/room/${createdRoom}$`));expect(ids).toHaveLength(2);expect(ids[1]).toBe(ids[0]);await expect(page.locator('.seats .seat')).toHaveCount(1);
});
