import { expect, type Browser, type Page } from '@playwright/test';
import type { View } from '../../src/shared/protocol';
const snapshots=new WeakMap<Page,View>();
const problems=new WeakMap<Page,string[]>();
export function observe(page:Page){if(problems.has(page))return;problems.set(page,[]);page.on('pageerror',e=>problems.get(page)!.push(e.message));page.on('console',m=>{if(m.type()==='error')problems.get(page)!.push(m.text());});page.on('websocket',socket=>socket.on('framereceived',frame=>{const raw=String(frame.payload);if(raw.startsWith('42')){const [event,value]=JSON.parse(raw.slice(2));if(event==='state')snapshots.set(page,value);}}));}
export const state=(page:Page)=>snapshots.get(page)!;
export function clean(pages:Page[]){for(const p of pages)expect(problems.get(p)).toEqual([]);}
export async function invite(page:Page){await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.getByRole('button',{name:'Invite',exact:true}).click();await expect(page.getByRole('button',{name:'Copied',exact:true})).toBeVisible();return page.evaluate(()=>navigator.clipboard.readText());}
export async function create(page:Page,url='http://localhost:3100',name='Ada'){observe(page);await page.goto(url);await page.getByRole('textbox',{name:'Name',exact:true}).fill(name);await page.getByRole('button',{name:'Start game',exact:true}).click();await expect(page.locator('.game')).toHaveAttribute('data-phase','LOBBY');return invite(page);}
export async function join(browser:Browser,link:string,name:string){const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();observe(page);await page.goto(link);await page.getByRole('textbox',{name:'Name',exact:true}).fill(name);await page.getByRole('button',{name:'Join game',exact:true}).click();await expect(page.locator('.game')).toHaveAttribute('data-phase','LOBBY');return page;}
export async function start(pages:Page[]){for(const p of pages)await p.getByRole('button',{name:'Ready',exact:true}).click();const host=pages.find(p=>state(p).host===state(p).you)!;await host.getByRole('button',{name:'Start game',exact:true}).click();}
export async function peek(pages:Page[]){for(const p of pages){await expect(p.locator('.seat.own .card-front img')).toHaveCount(2);for(const i of [1,3])await expect(p.locator(`.seat.own [data-slot="${i}"] .card-front img`)).toHaveCount(1);await expect(p.locator('.seat:not(.own) .card-front img')).toHaveCount(0);await expect(p.locator('.seat.own [data-slot]:enabled')).toHaveCount(0);}for(const p of pages){await expect(p.locator('.game')).toHaveAttribute('data-phase','INTER_TURN');await expect(p.locator('.seat.own .card-front img')).toHaveCount(0);}}
export async function nextActor(pages:Page[]){let actor:Page|undefined;await expect.poll(async()=>{for(const p of pages)if(await p.getByRole('button',{name:'Draw from draw pile',exact:true}).isEnabled()){actor=p;return true;}return false;},{timeout:15000}).toBe(true);return actor!;}
export async function turn(pages:Page[],slot?:number){const page=await nextActor(pages);await page.getByRole('button',{name:'Draw from draw pile',exact:true}).click();const pending=page.locator('.seat.own .pending-card');await expect(pending).toBeEnabled();if(slot===undefined)await pending.click();else await page.locator(`.seat.own [data-slot="${slot}"]`).click();return page;}
