import { test,expect } from '@playwright/test';
import { writeFileSync } from 'node:fs';
import { create,join,start,peek,nextActor,state,clean } from './helpers';

test('Invite gives honest clipboard feedback and a selectable fallback',async({page})=>{
 const link=await create(page);await expect(page.getByRole('button',{name:'Invite',exact:true})).toBeVisible({timeout:4000});await expect(page.getByRole('button',{name:'Invite',exact:true}).locator('svg,img')).toHaveCount(0);
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied');}}}));
 await page.getByRole('button',{name:'Invite',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Couldn’t copy');await expect(page.getByRole('textbox',{name:'Invite link'})).toHaveValue(link);await expect(page.getByRole('button',{name:'Copied',exact:true})).toHaveCount(0);
 await page.getByRole('textbox',{name:'Invite link'}).focus();expect(await page.getByRole('textbox',{name:'Invite link'}).evaluate((el:HTMLInputElement)=>el.selectionEnd!-el.selectionStart!)).toBe(link.length);
});

test('automatic initial peek is private, timed, and resumes without restarting after refresh',async({browser,page})=>{
 const link=await create(page);const guest=await join(browser,link,'Bea');await start([page,guest]);await expect(page.locator('.own .card-front img')).toHaveCount(2);const timing=state(page).initialPeek!;expect(timing.hideAt-timing.revealAt).toBe(3360);await expect(guest.locator('.opponent .card-front img')).toHaveCount(0);await expect(page.locator('.own [data-slot]:enabled')).toHaveCount(0);await expect(page.locator('[role=timer]')).toHaveCount(0);await page.waitForFunction(()=>{const a=document.querySelector('.own [data-slot="1"] .card-face')?.getAnimations()[0];return Number(a?.currentTime)>500;});const frames=await page.locator('.own [data-slot="1"] .card-face').evaluate(el=>(el.getAnimations()[0].effect as KeyframeEffect).getKeyframes());expect((frames[2].offset!-frames[1].offset!)*3720).toBeCloseTo(3000,0);await page.screenshot({path:'artifacts/automatic-peek.png'});
 await page.reload();await expect(page.locator('.own .card-front img')).toHaveCount(2);const remaining=state(page).initialPeek!.hideAt-state(page).paused!.since;await expect.poll(()=>state(guest).players.every(p=>p.connected)).toBe(true);await guest.getByRole('button',{name:'Resume game'}).click();await expect.poll(()=>state(page).paused).toBeUndefined();expect(state(page).initialPeek!.hideAt-state(page).restartAt).toBeCloseTo(remaining,0);await expect(page.locator('.game')).toHaveAttribute('data-phase','INTER_TURN');await expect(page.locator('.own .card-front img')).toHaveCount(0);await page.reload();await expect(page.locator('.game')).toHaveAttribute('data-phase','INTER_TURN');await expect(page.locator('.own .card-front img')).toHaveCount(0);await guest.context().close();
});

test('draw, replace and direct discard retain private faces, stable identity and matching timing',async({browser,page})=>{
 const link=await create(page);const guest=await join(browser,link,'Bea');const pages=[page,guest];await start(pages);await peek(pages);const actor=await nextActor(pages),other=pages.find(p=>p!==actor)!;
 await actor.setViewportSize({width:1180,height:820});const pile=actor.getByRole('button',{name:'Draw from draw pile',exact:true});const from=await pile.boundingBox();const to=await actor.locator('.seat.own .pending-card').boundingBox();
 // Sample actual frames without changing animation clocks or application state.
 await actor.evaluate(()=>{const samples:{x:number;y:number;t:number}[]=[];(window as unknown as {motionSamples:typeof samples}).motionSamples=samples;const stop=performance.now()+1200;const frame=()=>{const el=document.querySelector('.flying-card[data-motion="draw"]');if(el){const r=el.getBoundingClientRect();samples.push({x:r.x,y:r.y,t:performance.now()});}if(performance.now()<stop)requestAnimationFrame(frame);};requestAnimationFrame(frame);});
 await pile.evaluate(el=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});
 await expect(actor.locator('.flying-card[data-motion="draw"]')).toHaveCount(1);await actor.waitForFunction(()=>{const node=document.querySelector('.flying-card[data-motion=draw]');return Number(node?.getAnimations()[0]?.effect?.getComputedTiming().progress)>=.3;});await expect(pile.locator('.card-face')).toBeVisible();await actor.screenshot({path:'artifacts/draw-mid-landscape.png'});await other.screenshot({path:'artifacts/draw-private-observer.png'});
 const held=state(actor).held!;expect(held.id).toBeTruthy();expect(state(other).held?.value).toBeUndefined();expect(state(other).movements.filter(m=>m.kind==='draw').at(-1)?.value).toBeUndefined();await expect(other.locator('.pending-card .card-front img')).toHaveCount(0);
 await expect(actor.locator('.seat.own .pending-card')).toBeEnabled();expect(state(actor).held?.id).toBe(held.id);expect(state(actor).turn).toBe(0);
 const samples=await actor.evaluate(()=>(window as unknown as {motionSamples:{x:number;y:number;t:number}[]}).motionSamples);expect(samples.length).toBeGreaterThan(3);const intervals=samples.slice(1).map((s,i)=>s.t-samples[i].t).sort((a,b)=>a-b);const medianFrameMs=intervals[Math.floor(intervals.length/2)];expect(medianFrameMs).toBeLessThan(50);writeFileSync('artifacts/motion-samples.json',JSON.stringify({viewport:'1180x820',medianFrameMs,samples},null,2));expect(samples.some(s=>s.x>Math.min(from!.x,to!.x)+5&&s.x<Math.max(from!.x,to!.x)-5)).toBe(true);expect(Math.abs(samples.at(-1)!.x-to!.x)).toBeLessThan(Math.abs(samples[0].x-to!.x));
 const slot=actor.locator('.seat.own [data-slot="0"]');const slotBefore=await slot.boundingBox();await slot.click();await expect(actor.locator('.flying-card[data-motion="replace"]')).toHaveCount(1);await expect(actor.locator('.flying-card[data-motion="discard"]')).toHaveCount(1);await actor.waitForFunction(()=>Number(document.querySelector('.flying-card[data-motion=replace]')?.getAnimations()[0]?.effect?.getComputedTiming().progress)>=.3);await actor.screenshot({path:'artifacts/replace-mid-landscape.png'});await expect(actor.locator('.flying-card')).toHaveCount(0);await expect(slot.locator('.card-front img')).toHaveCount(0);await actor.mouse.move(5,5);await expect.poll(async()=>Math.abs((await slot.boundingBox())!.y-slotBefore!.y)).toBeLessThan(.1);expect(state(actor).held).toBeUndefined();
 // Resolve any legitimate special produced by the random outgoing grid card.
 while(state(actor).effects.length){const id=state(actor).effects[0].id;await actor.getByRole('button',{name:'Skip',exact:true}).click();await expect.poll(()=>state(actor).effects[0]?.id).not.toBe(id);}
 const next=await nextActor(pages);const top=state(next).discard;await next.getByRole('button',{name:'Draw from discard pile',exact:true}).click();await expect(next.locator('.seat.own .pending-card')).toHaveAttribute('data-held-id',/\S+/);await expect(next.locator('.seat.own .pending-card')).toBeDisabled();expect(state(next).held?.source).toBe('discard');expect(state(next).held?.value).toBe(top);
 await expect(next.locator('.seat.own [data-slot="1"]')).toBeEnabled();await next.locator('.seat.own [data-slot="1"]').click();await expect.poll(()=>state(next).held).toBeUndefined();
 while(state(next).effects.length){const id=state(next).effects[0].id;await next.getByRole('button',{name:'Skip',exact:true}).click();await expect.poll(()=>state(next).effects[0]?.id).not.toBe(id);}
 const rotating=await nextActor(pages);await rotating.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await expect(rotating.locator('.flying-card[data-motion=draw]')).toHaveCount(1);const rotatingId=state(rotating).held?.id;await rotating.setViewportSize({width:820,height:1180});await expect(rotating.locator('.game')).toHaveAttribute('data-orientation','portrait');await expect(rotating.locator('.seat.own .pending-card')).toBeEnabled();expect(state(rotating).held?.id).toBe(rotatingId);await expect(rotating.locator('.flying-card')).toHaveCount(0);await rotating.screenshot({path:'artifacts/pending-after-rotation.png'});await rotating.locator('.seat.own .pending-card').click();
 const reduced=await nextActor(pages);await reduced.emulateMedia({reducedMotion:'reduce'});await reduced.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await expect(reduced.locator('.seat.own .pending-card')).toHaveClass(/occupied/);await expect(reduced.locator('.flying-card')).toHaveCount(0);await reduced.screenshot({path:'artifacts/draw-reduced-motion.png'});await expect(reduced.locator('.seat.own .pending-card')).toBeEnabled();await reduced.locator('.seat.own .pending-card').click();await expect.poll(()=>state(reduced).held).toBeUndefined();expect(state(reduced).unlockAt-state(reduced).visualUntil).toBeGreaterThanOrEqual(1000);clean(pages);await guest.context().close();
});

test('turn markers, caller crown and gold button are independent; call bursts once',async({browser,page})=>{
 const link=await create(page);const guest=await join(browser,link,'Bea');const pages=[page,guest];await start(pages);await peek(pages);
 for(let i=0;i<3;i++){const actor=await nextActor(pages);await actor.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await expect(actor.locator('.seat.own .pending-card')).toBeEnabled();await actor.locator('.seat.own .pending-card').click();await expect.poll(()=>state(page).held).toBeUndefined();await expect(page.locator('.turn-seat')).toHaveAttribute('data-seat',state(page).next);expect(state(page).open).toBe(true);
  if(i===2){await expect(actor.getByRole('button',{name:'ARCHDUKE!',exact:true})).toBeEnabled();await expect(actor.locator('.archduke-button')).toHaveClass(/available/);for(const p of pages)await p.evaluate(()=>{const w=window as unknown as {bursts:number};w.bursts=0;new MutationObserver(records=>{for(const r of records)for(const node of r.addedNodes)if(node instanceof Element&&node.matches('.call-burst'))w.bursts++;}).observe(document.body,{childList:true,subtree:true});});await actor.getByRole('button',{name:'ARCHDUKE!',exact:true}).click();await expect(actor.locator('.call-burst')).toHaveCount(1);await actor.waitForFunction(()=>Number(document.querySelector('.call-burst')?.getAnimations()[0]?.currentTime??0)>600);const wave=await actor.locator('.call-burst').boundingBox(),origin=await actor.locator('.archduke-button').boundingBox();const viewport=actor.viewportSize()!;const reach=Math.hypot(viewport.width/2,viewport.height-(origin!.y+origin!.height/2));expect(wave!.width/2).toBeGreaterThan(reach*.5);expect(wave!.width/2).toBeLessThan(reach*1.1);await actor.screenshot({path:'artifacts/call-burst-mid.png'});for(const p of pages){await expect(p.locator('.archduke-button')).toHaveClass(/called/);await expect(p.locator('.archduke-button')).toHaveCSS('background-color','rgb(251, 180, 99)');await expect(p.locator('.archduke-button')).toHaveCSS('border-color','rgb(27, 30, 67)');await expect(p.locator('.game')).toHaveCSS('background-color','rgb(208, 213, 217)');await expect(p.locator('.opponent-strip')).toHaveCSS('background-color','rgb(188, 197, 206)');await expect(p.locator('.caller-name')).toHaveCSS('color','rgb(251, 180, 99)');await expect(p.locator('.caller-crown')).toHaveAttribute('src','/graphics/crown.png');await expect(p.locator('.turn-seat')).not.toHaveAttribute('data-seat',state(actor).you);}await expect(page.locator('.call-burst')).toHaveCount(0);for(const p of pages)expect(await p.evaluate(()=>(window as unknown as {bursts:number}).bursts)).toBe(1);expect(await page.locator('.game').evaluate(el=>getComputedStyle(el,'::after').content)).toBe('none');await page.screenshot({path:'artifacts/called-crown.png'});await guest.reload();await expect(guest.locator('.archduke-button')).toHaveClass(/called/);await expect(guest.locator('.call-burst')).toHaveCount(0);}
 }
 await expect(page.locator('.turn-marker,.caller-indicator')).toHaveCount(0);clean(pages);await guest.context().close();
});

test('reduced-motion call uses one gentle fade and never replays after refresh',async({browser,page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});const link=await create(page);const guest=await join(browser,link,'Bea');await guest.emulateMedia({reducedMotion:'reduce'});const pages=[page,guest];await start(pages);await peek(pages);const actor=await nextActor(pages);await actor.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await expect(actor.locator('.seat.own .pending-card')).toBeEnabled();await actor.locator('.seat.own .pending-card').click();await expect(actor.locator('.archduke-button')).toBeEnabled();await actor.locator('.archduke-button').click();await expect(actor.locator('.call-burst')).toHaveAttribute('data-reduced','true');expect(await actor.locator('.call-burst').evaluate(el=>el.getAnimations()[0].effect instanceof KeyframeEffect&&(el.getAnimations()[0].effect as KeyframeEffect).getKeyframes().every(frame=>!('transform' in frame)))).toBe(true);await actor.screenshot({path:'artifacts/call-reduced-motion.png'});await expect(actor.locator('.call-burst')).toHaveCount(0);await actor.reload();await expect(actor.locator('.archduke-button')).toHaveClass(/called/);await expect(actor.locator('.call-burst')).toHaveCount(0);clean(pages);await guest.context().close();
});

test('waiting slots stay centered through readiness and dealing; Invite stays transparent',async({browser,page})=>{
 const link=await create(page);const guest=await join(browser,link,'Bea');const pages=[page,guest];
 for(const [width,height] of [[1280,800],[1440,900],[1920,1080],[820,1180],[1180,820]]){await page.setViewportSize({width,height});await expect(page.locator('.game')).not.toHaveClass(/resizing/);await expect(page.locator('.waiting-slot')).toHaveCount(8);await expect(page.locator('.card-front img')).toHaveCount(0);await expect(page.locator('[data-endpoint=discard] img')).toHaveCount(0);await expect(page.locator('[data-endpoint=draw] img')).toBeVisible();for(const seat of await page.locator('.seat').all()){const name=await seat.locator('.seat-heading').boundingBox(),hand=await seat.locator('.card-grid').boundingBox();expect(name!.x+name!.width/2).toBeCloseTo(hand!.x+hand!.width/2,1);}await page.screenshot({path:`artifacts/waiting-${width}x${height}.png`});}
 await expect(page.getByRole('button',{name:'Start game',exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Ready',exact:true}).click();await expect(page.getByRole('button',{name:'Ready',exact:true})).toHaveCount(0);await expect(page.locator('.own .ready-check')).toBeVisible();await expect(page.locator('.waiting-slot')).toHaveCount(8);await page.screenshot({path:'artifacts/waiting-ready.png'});await guest.getByRole('button',{name:'Ready',exact:true}).click();await expect(page.getByRole('button',{name:'Start game',exact:true})).toBeVisible();const before=await page.locator('.own .waiting-slot').first().boundingBox();await page.getByRole('button',{name:'Start game',exact:true}).click();await expect(page.locator('.own [data-slot]')).toHaveCount(4);expect(await page.locator('.own [data-slot]').first().boundingBox()).toEqual(before);await page.screenshot({path:'artifacts/dealing-slots.png'});await peek(pages);
 await expect(page.getByRole('button',{name:'Invite',exact:true})).toBeVisible();await page.getByRole('button',{name:'Invite',exact:true}).hover();await expect(page.getByRole('button',{name:'Invite',exact:true})).toHaveCSS('background-color','rgba(0, 0, 0, 0)');await expect(page.getByRole('button',{name:'Scores',exact:true})).toHaveCount(0);expect(await page.locator('.turn-seat .name-mark').evaluate(el=>getComputedStyle(el,'::after').content)).toBe('none');clean(pages);await guest.context().close();
});


test('large central-card flips remain below opponents and inside the viewport',async({browser,page})=>{const link=await create(page);const guest=await join(browser,link,'Motion guest');const pages=[page,guest];await start(pages);await peek(pages);const actor=await nextActor(pages);await actor.setViewportSize({width:1920,height:1080});await expect(actor.locator('.game')).not.toHaveClass(/resizing/);
 const sample=actor.evaluate(()=>new Promise<{top:number;bottom:number;strip:number}[]>(resolve=>{const rows:{top:number;bottom:number;strip:number}[]=[];const end=performance.now()+1600;const frame=()=>{const el=document.querySelector('.flying-card .card-face');if(el){const r=el.getBoundingClientRect();rows.push({top:r.top,bottom:r.bottom,strip:document.querySelector('.opponent-strip')!.getBoundingClientRect().bottom});}if(performance.now()<end)requestAnimationFrame(frame);else resolve(rows);};frame();}));
 await actor.getByRole('button',{name:'Draw from draw pile',exact:true}).click();await actor.waitForFunction(()=>Number(document.querySelector('.flying-card .card-face')?.getAnimations()[0]?.currentTime??0)>150);await actor.screenshot({path:'artifacts/large-draw-mid.png'});const rows=await sample;writeFileSync('artifacts/large-motion-bounds.json',JSON.stringify(rows,null,2));console.log({frames:rows.length,minTop:Math.min(...rows.map(r=>r.top)),strip:rows[0]?.strip,maxBottom:Math.max(...rows.map(r=>r.bottom))});expect(rows.length).toBeGreaterThan(5);for(const row of rows){expect(row.top).toBeGreaterThanOrEqual(row.strip);expect(row.bottom).toBeLessThanOrEqual(1080);}expect(state(pages.find(p=>p!==actor)!).held?.value).toBeUndefined();await expect(actor.getByRole('button',{name:'Discard drawn card',exact:true})).toBeEnabled();await actor.getByRole('button',{name:'Discard drawn card',exact:true}).click();clean(pages);await guest.context().close();
});
