import { test,expect,type Page,type Browser } from '@playwright/test';
import { createApp } from '../../src/server/app';
import { config } from '../../src/server/config';
import { deck } from '../../src/engine/model';
import { create,join,state,clean } from './helpers';

async function setup(page:Page,browser:Browser,count=2,reduced=false){
 let now=Date.now();const app=createApp(config({PUBLIC_ORIGIN:'http://localhost:3102',PORT:'3102',NODE_ENV:'test'}),undefined,{now:()=>now,randomInt:n=>n-1,motion:500,delay:1000,peek:3000,grace:60000,restart:1000});await new Promise<void>(r=>app.http.listen(3102,r));
 const link=await create(page,'http://localhost:3102'),pages=[page];for(let i=1;i<count;i++)pages.push(await join(browser,link,['Ada','Bea','Cal','Dee','Eli','Fay'][i]));const room=app.rooms.rooms.get(state(page).room)!;
 for(const p of pages){await p.clock.install({time:now-1000});await p.clock.pauseAt(now);await p.emulateMedia({reducedMotion:reduced?'reduce':'no-preference'});await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));}
 async function advance(ms:number){now+=ms;await app.rooms.timers();await Promise.all(pages.map(p=>p.clock.runFor(ms)));for(const p of pages){await p.evaluate(()=>document.dispatchEvent(new Event('visibilitychange')));await expect.poll(()=>state(p).serverNow).toBe(now);}}
 await app.rooms.transaction(room,({state:s})=>{const cards=deck();s.players.forEach(p=>{p.slots=Array.from({length:4},(_,i)=>({card:cards.pop()!,rev:1,row:i%2,column:Math.floor(i/2)}));p.columns=2;});s.game=1;s.round=1;s.phase='INTER_TURN';s.open=true;s.window='window';s.next=s.players[1].id;s.discard=[cards.pop()!];s.deck=cards;s.effects=[{id:'peek-1',actor:s.players[0].id,kind:12}];s.seq++;});
 await expect(page.locator('.opponent [data-slot]')).toHaveCount((count-1)*4);await advance(500);
 const target=()=>page.locator(`.opponent[data-seat="${state(pages[1]).you}"] [data-slot="2"]`);
 const add=async(id:string)=>{await app.rooms.transaction(room,({state:s})=>{s.effects=[{id,actor:s.players[0].id,kind:12}];s.seq++;});await expect.poll(()=>state(page).effects[0]?.id).toBe(id);};
 return {app,room,pages,target,advance,add,now:()=>now,close:async()=>{for(const p of pages.slice(1))await p.context().close();await app.close();}};
}
for(const reduced of [false,true])test(`opponent Peek opens privately at hand center and returns without duplicates (${reduced?'reduced':'full'} motion)`,async({browser,page})=>{
 const f=await setup(page,browser,3,reduced);try{
  const target=f.target(),grid=target.locator('..'),original=await target.elementHandle(),before=await grid.boundingBox(),others=await grid.locator('[data-slot]:not([data-slot="2"])').evaluateAll(es=>es.map(e=>({slot:e.getAttribute('data-slot'),transform:(e as HTMLElement).style.transform,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y}))),commands:string[]=[];
  const base=f.app.rooms.command.bind(f.app.rooms);f.app.rooms.command=async(...args)=>{if((args[3] as {type:string}).type==='done')commands.push((args[3] as {id:string}).id);return base(...args);};
  await target.click();await expect.poll(()=>state(page).effects[0].peek).toBeDefined();await f.advance(20);const card=page.locator('.opponent-peek-card'),event=state(page).effects[0],source=await target.boundingBox(),privateValue=state(page).players[1].slots[2].value!;
  await expect(card).toHaveCount(1);await expect(target).toHaveAttribute('data-peek-lifted','true');await expect(target.locator('.card-face')).toHaveCSS('visibility','hidden');await expect(target.locator('.card-front img')).toHaveCount(0);expect(await grid.boundingBox()).toEqual(before);expect(await original!.evaluate(el=>el.isConnected)).toBe(true);
  const origin=await card.evaluate(el=>({x:parseFloat((el as HTMLElement).style.left),width:parseFloat((el as HTMLElement).style.width)}));expect(origin.x).toBeCloseTo(source!.x,1);expect(origin.width).toBeCloseTo(source!.width,1);
  for(const other of f.pages.slice(1)){await expect(other.locator('.opponent-peek-card')).toHaveCount(0);await expect(other.locator('.seat .card-front img')).toHaveCount(0);const v=state(other);expect(v.effects[0].peek).toBeUndefined();expect(v.players[1].slots[2].value).toBeUndefined();expect(JSON.stringify(v.effects[0])).not.toContain('value');}
  await expect(card.locator('.card-front img')).toHaveAttribute('alt',`Card ${privateValue}`);if(!reduced){await expect(card).toHaveAttribute('data-phase','opening');await expect(card).toHaveCSS('pointer-events','none');await f.advance(230);const mid=await card.boundingBox();expect(mid!.width).toBeGreaterThan(source!.width);expect(mid!.width).toBeLessThan(source!.width*1.6);expect(await card.locator('.card-face').evaluate(el=>new DOMMatrix(getComputedStyle(el).transform).m11)).toBeLessThan(.99);await page.screenshot({path:'artifacts/opponent-peek-opening.png'});}else await f.advance(230);
  await f.advance(250);await expect(card).toHaveAttribute('data-phase','open');expect(await page.locator('.game').evaluate(el=>el.scrollLeft)).toBe(0);await expect(card).toHaveCSS('pointer-events','auto');const expanded=await card.boundingBox(),hand=await grid.boundingBox();expect(expanded!.width/source!.width).toBeCloseTo(1.6,1);expect(expanded!.width/expanded!.height).toBeCloseTo(5/7,2);expect(expanded!.x+expanded!.width/2).toBeCloseTo(hand!.x+hand!.width/2,1);expect(expanded!.y+expanded!.height/2).toBeCloseTo(hand!.y+hand!.height/2,1);expect(expanded!.width).toBeLessThan(hand!.width);expect(expanded!.height).toBeLessThan(hand!.height);expect(others).toEqual(await grid.locator('[data-slot]:not([data-slot="2"])').evaluateAll(es=>es.map(e=>({slot:e.getAttribute('data-slot'),transform:(e as HTMLElement).style.transform,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y}))));await page.screenshot({path:`artifacts/opponent-peek-${reduced?'reduced':'expanded'}.png`});
  await f.advance(2999);await expect(card).toHaveAttribute('data-phase','open');expect(state(page).effects[0].id).toBe(event.id);await f.advance(1);await expect(card).toHaveAttribute('data-phase','closing');await expect(target.locator('.card-face')).toHaveCSS('visibility','hidden');
  await f.advance(reduced?40:250);await card.evaluate((el,elapsed)=>{for(const a of el.getAnimations({subtree:true})){a.pause();a.currentTime=elapsed;}},reduced?40:250);expect((await card.boundingBox())!.width).toBeLessThan(expanded!.width);await page.screenshot({path:`artifacts/opponent-peek-${reduced?'reduced':'full'}-closing.png`});await f.advance(reduced?40:250);await expect(card).toHaveCount(0);await expect(target.locator('.card-face')).toBeVisible();await expect(target.locator('.card-front img')).toHaveCount(0);expect(await grid.boundingBox()).toEqual(before);expect(await original!.evaluate(el=>el.isConnected)).toBe(true);expect(commands).toEqual([]);
  await f.add('peek-2');await target.click();await f.advance(500);await expect(card).toHaveAttribute('data-phase','open');await card.evaluate(el=>{(el as HTMLButtonElement).click();(el as HTMLButtonElement).click();});await f.advance(20);await expect.poll(()=>commands.length).toBe(1);await expect.poll(()=>state(page).effects.length).toBe(0);await f.advance(500);await expect(card).toHaveCount(0);await expect(target).not.toHaveAttribute('data-peek-lifted');clean(f.pages);
 }finally{await f.close();}
});

test('opening clicks queue one close; own-card Peek and teardown keep established behavior',async({browser,page})=>{
 const f=await setup(page,browser);try{
  await f.target().click({position:{x:3,y:20}});await expect.poll(()=>state(page).effects[0]?.peek).toBeDefined();await f.advance(200);const card=page.locator('.opponent-peek-card'),r=await card.boundingBox();await page.mouse.click(r!.x+r!.width/2,r!.y+r!.height/2);await f.advance(200);expect(state(page).effects[0].id).toBe('peek-1');await expect(card).toHaveAttribute('data-phase','opening');await f.advance(100);await expect.poll(()=>state(page).effects.length).toBe(0);await f.advance(500);await expect(card).toHaveCount(0);
  await f.add('own-peek');await page.locator('.own [data-slot="0"]').click();await expect(page.locator('.own [data-slot="0"] .card-front img')).toHaveCount(1);await expect(card).toHaveCount(0);await page.locator('.own [data-slot="0"]').click();await expect.poll(()=>state(page).effects.length).toBe(0);
  await f.advance(500);await f.add('exit-peek');await f.target().click({position:{x:3,y:20}});await expect.poll(()=>state(page).effects[0]?.peek).toBeDefined();await f.advance(500);await expect(card).toBeVisible();await page.getByRole('button',{name:'Exit',exact:true}).click();await expect(page.locator('.room-lobby')).toBeVisible();await expect(card).toHaveCount(0);await expect(page.locator('[data-peek-lifted]')).toHaveCount(0);
 }finally{await f.close();}
});

test('six-player portrait, landscape and resize keep the selected hand as the anchor; reconnect restores remaining view',async({browser,page})=>{
 const f=await setup(page,browser,6);try{
  for(const [iteration,viewport] of [{width:820,height:1180},{width:1180,height:820},{width:390,height:844}].entries()){
   if(iteration)await f.app.rooms.transaction(f.room,({state:s})=>{const p=s.players[1];for(const row of [0,1])p.slots.push({card:s.deck.pop()!,rev:1,row,column:iteration+1});p.columns=iteration+2;s.seq++;});
   await page.setViewportSize(viewport);await f.advance(100);await f.target().click({position:{x:3,y:20}});await expect.poll(()=>state(page).effects[0]?.peek).toBeDefined();await f.advance(500);const card=page.locator('.opponent-peek-card');await expect(card).toHaveAttribute('data-phase','open');const rect=await card.boundingBox(),hand=await f.target().locator('..').boundingBox();expect(rect!.x+rect!.width/2).toBeCloseTo(hand!.x+hand!.width/2,1);expect(rect!.y+rect!.height/2).toBeCloseTo(hand!.y+hand!.height/2,1);expect(rect!.x).toBeGreaterThanOrEqual(8);expect(rect!.x+rect!.width).toBeLessThanOrEqual(viewport.width-8);expect(rect!.y).toBeGreaterThanOrEqual((await page.locator('.game-header').boundingBox())!.height);expect(rect!.y+rect!.height).toBeLessThanOrEqual((await page.locator('.personal-area').boundingBox())!.y);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(viewport.width);await page.screenshot({path:`artifacts/opponent-peek-six-${viewport.width}.png`});await card.click();await f.advance(20);await expect.poll(()=>state(page).effects.length).toBe(0);await f.advance(500);await f.add(`peek-${viewport.width}`);
  }
  await page.setViewportSize({width:1440,height:900});await f.target().click({position:{x:3,y:20}});await expect.poll(()=>state(page).effects[0]?.peek).toBeDefined();await f.advance(500);await page.setViewportSize({width:820,height:1180});await f.advance(100);let card=page.locator('.opponent-peek-card');const rect=await card.boundingBox(),hand=await f.target().locator('..').boundingBox();expect(rect!.x+rect!.width/2).toBeCloseTo(hand!.x+hand!.width/2,1);const before=state(page).effects[0];await page.reload();await expect.poll(()=>state(page).effects[0]?.id).toBe(before.id);await expect.poll(()=>state(page).paused).toBeUndefined();await f.advance(1100);card=page.locator('.opponent-peek-card');await expect(card).toHaveAttribute('data-phase','open');const until=state(page).effects[0].viewUntil!;await f.advance(until-f.now());await f.advance(500);await expect(card).toHaveCount(0);await page.reload();await expect(page.locator('.game')).toBeVisible();await expect(card).toHaveCount(0);await expect(page.locator('.seat .card-front img')).toHaveCount(0);clean(f.pages);
 }finally{await f.close();}
});

for(const count of [4,5])test(`${count} players: Peek remains centered over the last opponent`,async({browser,page})=>{
 const f=await setup(page,browser,count);try{
  const seat=state(f.pages.at(-1)!).you,target=page.locator(`[data-seat="${seat}"] [data-slot="1"]`);await target.click();await expect.poll(()=>state(page).effects[0]?.peek).toBeDefined();await f.advance(500);const card=page.locator('.opponent-peek-card');await expect(card).toHaveAttribute('data-phase','open');const r=await card.boundingBox(),hand=await target.locator('..').boundingBox();expect(r!.x+r!.width/2).toBeCloseTo(hand!.x+hand!.width/2,1);expect(r!.y+r!.height/2).toBeCloseTo(hand!.y+hand!.height/2,1);await expect(target.locator('.card-face')).toHaveCSS('visibility','hidden');await f.advance(3500);await expect(card).toHaveCount(0);
 }finally{await f.close();}
});
