import { describe, it, expect } from 'vitest';
import { apply, project, tick, connection, startRound } from '../src/engine/engine.js';
import { assertCards, createState, newPlayer, deck, shuffle, matches, occupied, sum, type State, type Dependencies } from '../src/engine/model.js';
import type { Command, Target } from '../src/shared/protocol.js';
type Action = Command extends infer C ? C extends Command ? Omit<C,'id'|'game'|'round'> : never : never;
function fixture(count=2){let time=10000;let serial=0;const d:Dependencies={now:()=>time,randomInt:max=>max-1,delay:1000,motion:100,peek:3000,grace:60000,restart:1000};const s=createState('room','CODE','invite',newPlayer('p0','Player 0'));for(let i=1;i<count;i++)s.players.push(newPlayer(`p${i}`,`Player ${i}`));s.players.forEach(p=>{p.connected=true;p.ready=true;});
 const send=(who:string,a:Action)=>{const reply=apply(s,d,who,{...a,id:`a${++serial}`,game:s.game,round:s.round} as Command);assertCards(s);return reply;};send('p0',{type:'start'});
 const ref=(who='p0',index=0):Target=>({player:who,slot:index,rev:s.players.find(p=>p.id===who)!.slots[index].rev});
 const settle=()=>{time=Math.max(time,s.visualUntil,s.unlockAt);};
 const peek=()=>{time=Math.max(time,s.initialPeek!.revealAt);tick(s,d);time=s.initialPeek!.finishAt;tick(s,d);settle();};
 const draw=(who=s.next,source:'draw'|'discard'='draw')=>send(who,{type:'draw',source,window:s.window,turn:s.turn});
 const discard=(who=s.held!.owner,target?:Target)=>{settle();return send(who,{type:'resolveDraw',turn:s.turn,target});};
 const match=(who:string,indices:number[])=>send(who,{type:'match',window:s.window,slots:indices.map(i=>ref(who,i))});
 return {s,d,send,ref,settle,peek,draw,discard,match,setTime:(n:number)=>time=n,advance:(n:number)=>time+=n};
}
// Test-only allocation of the real multiset: no manufactured cards and no production fixture route.
function rig(s:State,hands:number[][],top:number,draws:number[]=[]){const all=deck();const take=(v:number)=>{const i=all.findIndex(c=>c.value===v);if(i<0)throw new Error(`Fixture exhausted ${v}`);return all.splice(i,1)[0];};s.players.forEach((p,i)=>p.slots=hands[i].map(value=>({rev:1,card:take(value)})));s.discard=[take(top)];const queued=draws.map(take);s.deck=[...all,...queued.reverse()];s.held=undefined;assertCards(s);}

describe('physical cards and private initial information',()=>{
 it('has the exact 104-card multiset and unbiased Fisher–Yates bounds',()=>{const cards=deck();expect(cards).toHaveLength(104);expect(new Set(cards.map(c=>c.id)).size).toBe(104);expect(Object.fromEntries([...new Set(cards.map(c=>c.value))].map(v=>[v,cards.filter(c=>c.value===v).length]))).toEqual({'-3':2,'0':4,'1':8,'2':8,'3':8,'4':8,'5':8,'6':8,'7':8,'8':8,'9':8,'10':8,'11':6,'12':8,'13':4});const bounds:number[]=[];shuffle(cards,n=>{bounds.push(n);return 0;});expect(bounds).toEqual(Array.from({length:103},(_,i)=>104-i));});
 for(const count of [2,6])it(`deals four at ${count} seats and hides all cards`,()=>{const f=fixture(count);expect(f.s.deck.length).toBe(104-count*4);for(const p of f.s.players){expect(occupied(p)).toBe(4);expect(project(f.s,f.d,p.id).players.flatMap(p=>p.slots).every(s=>s.value===undefined)).toBe(true);}assertCards(f.s);});
 it('automatically reveals only bottom cards for three full seconds after the flip',()=>{const f=fixture();const timing=f.s.initialPeek!;expect(project(f.s,f.d,'p0').players.flatMap(p=>p.slots).every(s=>s.value===undefined)).toBe(true);f.setTime(timing.revealAt);tick(f.s,f.d);expect(timing.hideAt-timing.revealAt-360).toBe(3000);for(const viewer of ['p0','p1']){const v=project(f.s,f.d,viewer);for(const p of v.players)expect(p.slots.filter(s=>s.value!==undefined).map(s=>s.index)).toEqual(p.id===viewer?[1,3]:[]);}f.setTime(timing.hideAt);tick(f.s,f.d);expect(f.s.phase).toBe('INITIAL_PEEK');f.setTime(timing.finishAt);tick(f.s,f.d);expect(f.s.phase).toBe('INTER_TURN');expect(project(f.s,f.d,'p0').players.flatMap(p=>p.slots).every(s=>s.value===undefined)).toBe(true);});
 it('initial discard never triggers an effect but initial matching does',()=>{const f=fixture();f.s.deck.push(...f.s.deck.splice(f.s.deck.findIndex(c=>c.value===1),1));f.peek();expect(f.s.effects).toHaveLength(0);rig(f.s,[[1,2],[3,4]],1);f.match('p0',[0]);expect(f.s.effects[0]).toMatchObject({actor:'p0',kind:1});});
});
describe('draws, matching, and authoritative boundaries',()=>{
 it('allows draw discard without activating a special and only one held card',()=>{const f=fixture();f.peek();rig(f.s,[[2,3],[4,5]],7,[12]);f.draw();expect(()=>f.draw()).toThrow();expect(project(f.s,f.d,'p0').held?.value).toBeUndefined();expect(project(f.s,f.d,'p1').held?.value).toBe(12);f.discard();expect(f.s.effects).toHaveLength(0);expect(f.s.discard.at(-1)?.value).toBe(12);});
 it('forces discard-pile replacement and preserves exact target positions',()=>{const f=fixture();f.peek();rig(f.s,[[2,3],[11,5]],7);f.draw('p1','discard');expect(f.s.discard).toHaveLength(0);expect(()=>f.discard()).toThrow(/must replace/);f.discard('p1',f.ref('p1',0));expect(f.s.discard.at(-1)?.value).toBe(11);expect(f.s.players[1].slots[0].card?.value).toBe(7);expect(f.s.effects[0].kind).toBe(11);});
 it('rejects early draws immediately and accepts exactly at the unlock boundary',()=>{const f=fixture();f.peek();f.setTime(f.s.unlockAt-1);expect(()=>f.draw()).toThrow(/protected/);expect(f.s.open).toBe(true);expect(f.s.held).toBeUndefined();f.setTime(f.s.unlockAt);f.draw();expect(f.s.open).toBe(false);});
 it('supports equivalence in both directions, competing matches, stable holes, and global drift',()=>{expect(matches(0,13)).toBe(true);expect(matches(13,0)).toBe(true);const f=fixture();f.peek();rig(f.s,[[0,2],[13,4]],13);const a=f.ref('p0',0),b=f.ref('p1',0);f.send('p0',{type:'match',window:f.s.window,slots:[a]});f.send('p1',{type:'match',window:f.s.window,slots:[b]});expect(f.s.players.every(p=>!p.slots[0].card&&p.slots[1].card)).toBe(true);expect(f.s.movements.filter(m=>m.kind==='penalty')).toHaveLength(0);});
 it('mixed batches keep wrong cards and charge one unknown card per failure',()=>{const f=fixture();f.peek();rig(f.s,[[7,2,7,3],[4,5]],7,[6,8]);const reply=f.match('p0',[0,1,2]);expect(reply.results).toEqual(['matched','wrong','matched']);f.match('p0',[3]);expect(f.s.players[0].slots).toHaveLength(6);expect(f.s.players[0].slots[4].card?.value).toBe(6);expect(f.s.discard.at(-1)?.value).toBe(7);const view=project(f.s,f.d,'p1');expect(view.players[0].slots[1].value).toBe(2);expect(view.players[0].slots[4].value).toBeUndefined();f.advance(10000);tick(f.s,f.d);expect(project(f.s,f.d,'p1').players[0].slots.every(x=>x.value===undefined)).toBe(true);});
 it('draw-first yields per-card late penalties with no reveal; older windows are stale',()=>{const f=fixture();f.peek();rig(f.s,[[7,2],[4,5]],7,[9,8]);const old=f.s.window;f.draw();expect(f.match('p0',[0]).code).toBe('LATE');f.match('p0',[1]);expect(f.s.players[0].slots).toHaveLength(4);expect(f.s.reveals).toHaveLength(0);f.discard();expect(()=>f.send('p0',{type:'match',window:old,slots:[f.ref()]})).toThrow(/obsolete/);f.match('p0',[0]);expect(f.s.players[0].slots).toHaveLength(5);});
 it('match-first moves the top before a draw and extends the protected delay',()=>{const f=fixture();f.peek();rig(f.s,[[0,2],[4,5]],13);f.match('p0',[0]);expect(()=>f.draw('p1','discard')).toThrow();f.settle();f.draw('p1','discard');expect(f.s.held?.card.value).toBe(0);});
 it('rejects duplicate selections and changed occupancy without penalties or information',()=>{const f=fixture();f.peek();rig(f.s,[[7,2],[4,5]],7);const ref=f.ref();expect(()=>f.send('p0',{type:'match',window:f.s.window,slots:[ref,ref]})).toThrow(/distinct/);f.match('p0',[0]);expect(()=>f.send('p0',{type:'match',window:f.s.window,slots:[ref]})).toThrow(/changed/);expect(f.s.movements.filter(m=>m.kind==='penalty')).toHaveLength(0);});
});
describe('FIFO special effects and immunity',()=>{
 for(const value of [1,11,12])it(`activates ${value} from a replaced grid but never a direct draw discard`,()=>{const f=fixture();f.peek();rig(f.s,[[3,4],[value,5]],7,[8]);f.draw();f.discard('p1',f.ref('p1',0));expect(f.s.effects[0].kind).toBe(value);});
 it('keeps matching open while another player is choosing a special action',()=>{const f=fixture();f.peek();rig(f.s,[[12,2],[12,5]],12);f.match('p0',[0]);expect(f.s.effects).toHaveLength(1);expect(project(f.s,f.d,'p1').open).toBe(true);f.match('p1',[0]);expect(f.s.effects.map(e=>[e.actor,e.kind])).toEqual([['p0',12],['p1',12]]);expect(()=>f.draw()).toThrow();});
 it('Give is unknown to both parties and appends without filling a hole',()=>{const f=fixture();f.peek();rig(f.s,[[1,2],[7,3]],1,[12]);f.match('p0',[0]);f.settle();f.send('p0',{type:'effect',effect:f.s.effects[0].id,recipient:'p1'});expect(f.s.players[1].slots[2].card?.value).toBe(12);expect(project(f.s,f.d,'p0').players[1].slots[2].value).toBeUndefined();expect(project(f.s,f.d,'p1').players[1].slots[2].value).toBeUndefined();expect(f.s.effects).toHaveLength(0);});
 it('Swap validates two different players, revisions and endpoints without revealing faces',()=>{const f=fixture();f.peek();rig(f.s,[[11,2],[7,3]],11);f.match('p0',[0]);f.settle();const id=f.s.effects[0].id;expect(()=>f.send('p0',{type:'effect',effect:id,targets:[f.ref('p1',0),f.ref('p1',1)]})).toThrow(/different/);f.send('p0',{type:'effect',effect:id,targets:[f.ref('p0',1),f.ref('p1',0)]});expect(f.s.players[0].slots[1].card?.value).toBe(7);expect(f.s.players[1].slots[0].card?.value).toBe(2);expect(project(f.s,f.d,'p0').players.flatMap(p=>p.slots).every(x=>x.value===undefined)).toBe(true);expect(f.s.movements.at(-1)).toMatchObject({kind:'swap',from:'p0:1',to:'p1:0'});expect(f.s.movements.at(-1)?.value).toBeUndefined();});
 it('Peek expires on the server, only the actor gets the face, Done works early',()=>{const f=fixture();f.peek();rig(f.s,[[12,12,2],[7,3]],12);f.match('p0',[0,1]);f.settle();f.send('p0',{type:'effect',effect:f.s.effects[0].id,targets:[f.ref('p1',0)]});expect(project(f.s,f.d,'p0').players[1].slots[0].value).toBe(7);expect(project(f.s,f.d,'p1').players[1].slots[0].value).toBeUndefined();f.setTime(f.s.effects[0].viewUntil!);tick(f.s,f.d);expect(project(f.s,f.d,'p0').players[1].slots[0].value).toBeUndefined();f.send('p0',{type:'effect',effect:f.s.effects[0].id,targets:[f.ref('p1',1)]});f.send('p0',{type:'done',effect:f.s.effects[0].id});expect(f.s.effects).toHaveLength(0);});
 for(const kind of [1,11,12] as const)it(`enforces caller immunity for ${kind}`,()=>{const f=fixture(3);f.peek();rig(f.s,[[2,3],[kind,5],[6,7]],kind);f.s.caller='p0';f.match('p1',[0]);f.settle();const e=f.s.effects[0];expect(()=>f.send('p1',{type:'effect',effect:e.id,...(kind===1?{recipient:'p0'}:{targets:kind===11?[f.ref('p0',0),f.ref('p2',0)]:[f.ref('p0',0)]})})).toThrow();f.send('p1',{type:'effect',effect:e.id,skip:true});expect(f.s.effects).toHaveLength(0);});
 it('auto-skips Swap when caller immunity leaves only one eligible player',()=>{const f=fixture();f.peek();rig(f.s,[[11,3],[7,5]],11);f.s.caller='p1';f.match('p0',[0]);expect(f.s.effects).toHaveLength(0);expect(f.s.activity[0]).toContain('no legal target');});
});
describe('Archduke and exact round termination',()=>{
 it('permits call after direct discard, caller keeps matching and each other seat gets one turn',()=>{const f=fixture(3);f.peek();rig(f.s,[[4,6],[5,8],[3,9]],7,[2,6,8]);expect(()=>f.send('p0',{type:'call',window:f.s.window,turn:f.s.turn})).toThrow();f.draw();f.discard();f.setTime(f.s.visualUntil);f.send('p2',{type:'call',window:f.s.window,turn:f.s.turn});expect(f.s.finalTurns).toEqual(['p0','p1']);f.match('p2',[0]);expect(f.s.players[2].slots).toHaveLength(3);for(const who of ['p0','p1']){f.settle();f.draw(who);f.discard(who);}expect(f.s.phase).toBe('FINAL_MATCH_WINDOW');expect(()=>f.draw('p2')).toThrow();expect(()=>f.send('p1',{type:'finish',window:f.s.window})).toThrow();f.settle();expect(()=>f.send('p2',{type:'finish',window:f.s.window})).toThrow();f.setTime(f.s.finalEndsAt!);tick(f.s,f.d);expect(f.s.history).toHaveLength(1);});
 it('draw-first closes the call opportunity; call-first is atomic',()=>{const f=fixture();f.peek();f.draw();f.discard();f.settle();const old=f.s.lastTurn!;const window=f.s.window;const turn=f.s.turn;f.draw();expect(()=>f.send(old,{type:'call',window,turn})).toThrow();});
 it('ends immediately after a last special-card match, cancels pending effects, and zero can lose',()=>{const f=fixture();f.peek();rig(f.s,[[1],[-3,0]],1);f.match('p0',[0]);expect(f.s.phase).toBe('ROUND_RESULTS');expect(f.s.effects).toHaveLength(0);expect(f.s.history[0][0]).toMatchObject({player:'p1',sum:-3});expect(()=>f.match('p1',[0])).toThrow();});
 it('stops batch and pending effect chain on zero, scoring exactly once',()=>{const f=fixture();f.peek();rig(f.s,[[11,11],[4,5]],11);const r=f.match('p0',[0,1]);expect(r.results).toEqual(['matched','matched']);expect(f.s.effects).toHaveLength(0);expect(f.s.history).toHaveLength(1);expect(()=>f.match('p0',[0])).toThrow();});
 it('applies one incorrect-call card before ranking, including negative penalty',()=>{const f=fixture();f.peek();rig(f.s,[[0],[2]],0,[-3]);f.s.caller='p1';f.match('p0',[0]);expect(f.s.players[1].slots).toHaveLength(2);expect(sum(f.s.players[1])).toBe(-1);expect(f.s.history[0][0].player).toBe('p1');expect(f.s.incorrectApplied).toBe(true);});
 it('does not penalize caller tied for the minimum',()=>{const f=fixture();f.peek();rig(f.s,[[0],[0]],0,[9]);f.s.caller='p1';f.match('p0',[0]);expect(f.s.players[1].slots).toHaveLength(1);expect(f.s.history[0][0].player).toBe('p0');});
 it('completes four rounds with placement totals, shared victory, next last-place starter, fresh reset',()=>{const f=fixture();for(let round=1;round<=4;round++){f.peek();const winner=round%2?'p0':'p1';rig(f.s,winner==='p0'?[[7],[8,9]]:[[8,9],[7]],7);f.match(winner,[0]);expect(f.s.history).toHaveLength(round);if(round<4){f.s.players.forEach(p=>p.ready=true);const last=f.s.history.at(-1)!.at(-1)!.player;f.send('p0',{type:'next'});expect(f.s.phase).toBe('LOBBY');expect(f.s.players.every(p=>p.slots.length===0&&!p.ready)).toBe(true);f.s.players.forEach(p=>{p.reviewingResults=false;p.ready=true;});f.send('p0',{type:'start'});expect(f.s.next).toBe(last);expect(f.s.players.every(p=>p.slots.length===4&&!p.initial&&!p.hidden)).toBe(true);}}expect(f.s.phase).toBe('GAME_RESULTS');expect(f.s.winners).toEqual(['p0','p1']);f.s.players.forEach(p=>{p.reviewingResults=false;p.ready=true;});f.send('p0',{type:'start'});expect(f.s.round).toBe(1);expect(f.s.history).toHaveLength(0);assertCards(f.s);});
 it('ranks equal sums by fewest cards then lowest single card',()=>{const f=fixture(4);f.peek();rig(f.s,[[0],[3],[1,2],[-3,6]],0);f.match('p0',[0]);expect(f.s.history[0].map(r=>r.player)).toEqual(['p0','p1','p3','p2']);});
 it('uses temporary tie-break cards without changing sums or conservation',()=>{const f=fixture(3);f.peek();rig(f.s,[[0],[3],[3]],0,[2,4]);f.match('p0',[0]);expect(f.s.history[0].map(r=>r.player)).toEqual(['p0','p1','p2']);expect(f.s.history[0][1].sum).toBe(3);expect(f.s.history[0][1].tie).toContain('Tie-break 2');assertCards(f.s);});
});
describe('supply, pause, reconnect, and stale commands',()=>{
 it('recycles all discards except top and never touches hands or held draw',()=>{const f=fixture();f.peek();const cards=f.s.deck;f.s.deck=[];f.s.discard=[...cards,...f.s.discard];const top=f.s.discard.at(-1)!;const hands=structuredClone(f.s.players.map(p=>p.slots));f.draw();expect(f.s.discard).toEqual([top]);expect(f.s.players.map(p=>p.slots)).toEqual(hands);expect(f.s.deck.length).toBe(cards.length-1);assertCards(f.s);});
 it('handles mandatory exhausted supply without cloning or dropping round placements',()=>{const f=fixture();f.peek();rig(f.s,[[2,3],[4,5]],7);f.s.players[1].slots.push(...f.s.deck.splice(0).map(card=>({rev:1,card})));f.match('p0',[0]);expect(f.s.paused?.reason).toBe('No cards available');expect(f.s.history).toHaveLength(0);assertCards(f.s);f.send('p0',{type:'redeal'});expect(f.s.round).toBe(1);expect(f.s.phase).toBe('INITIAL_PEEK');assertCards(f.s);});
 it('disconnect freezes private peek duration, transfers host and resumes when everyone reconnects',()=>{const f=fixture();f.peek();rig(f.s,[[12,2],[7,3]],12);f.match('p0',[0]);f.settle();f.send('p0',{type:'effect',effect:f.s.effects[0].id,targets:[f.ref('p1',0)]});const remaining=f.s.effects[0].viewUntil!-f.d.now();connection(f.s,f.d,'p0',false);expect(f.s.host).toBe('p1');f.advance(100000);tick(f.s,f.d);expect(f.s.effects).toHaveLength(1);expect(()=>f.send('p1',{type:'resume'})).toThrow(/reconnect/);connection(f.s,f.d,'p0',true);expect(f.s.paused).toBeUndefined();expect(f.s.effects[0].viewUntil!-f.d.now()).toBe(remaining+f.d.restart);});
 it('old round actions cannot affect a new deal',()=>{const f=fixture();f.peek();const old={id:'old',game:f.s.game,round:f.s.round,type:'match' as const,window:f.s.window,slots:[f.ref()]};rig(f.s,[[7],[8]],7);f.match('p0',[0]);startRound(f.s,f.d);expect(()=>apply(f.s,f.d,'p0',old)).toThrow(/earlier/);assertCards(f.s);});
});

describe('additional supply and race regressions',()=>{
 it('charges both an on-time wrong attempt and a later attempt after draw',()=>{const f=fixture();f.peek();rig(f.s,[[2,3],[4,5]],7,[8,9]);f.match('p0',[0]);f.settle();f.draw();expect(f.match('p0',[1]).code).toBe('LATE');expect(f.s.players[0].slots.length).toBe(4);assertCards(f.s);});
 for(const kind of ['give','penalty'])it(`recycles for ${kind} without revealing the unknown new card`,()=>{const f=fixture();f.peek();rig(f.s,[[1,2],[3,4]],kind==='give'?1:7);const recycled=f.s.deck.splice(0);f.s.discard=[...recycled,...f.s.discard];const top=f.s.discard.at(-1)!;f.match('p0',[0]);if(kind==='give'){f.settle();f.send('p0',{type:'effect',effect:f.s.effects[0].id,recipient:'p1'});}expect(f.s.deck.length).toBeGreaterThan(0);expect(f.s.discard).toHaveLength(1);if(kind==='penalty')expect(f.s.discard[0]).toEqual(top);for(const actor of ['p0','p1']){const recipient=project(f.s,f.d,actor).players[kind==='give'?1:0];expect(recipient.slots.at(-1)?.value).toBeUndefined();}assertCards(f.s);});
 it('a changed target during private selection rejects the effect without revealing its new occupant',()=>{const f=fixture();f.peek();rig(f.s,[[12,2],[12,4]],12);f.match('p0',[0]);const target=f.ref('p1',0);f.match('p1',[0]);f.settle();expect(()=>f.send('p0',{type:'effect',effect:f.s.effects[0].id,targets:[target]})).toThrow(/changed/);expect(project(f.s,f.d,'p0').players[1].slots[0].value).toBeUndefined();expect(f.s.effects).toHaveLength(2);});
 it('preserves completed round placements during an exhausted-round redeal',()=>{const f=fixture();f.peek();rig(f.s,[[7],[8]],7);f.match('p0',[0]);f.s.players.forEach(p=>p.ready=true);f.send('p0',{type:'next'});expect(f.s.phase).toBe('LOBBY');expect(f.s.players.every(p=>p.slots.length===0&&!p.ready)).toBe(true);f.s.players.forEach(p=>{p.reviewingResults=false;p.ready=true;});f.send('p0',{type:'start'});const history=structuredClone(f.s.history);f.peek();f.draw();f.discard();expect(f.s.next).toBe('p0');rig(f.s,[[2,3],[4,5]],7);f.s.players[1].slots.push(...f.s.deck.splice(0).map(card=>({rev:1,card})));f.match('p0',[0]);f.send('p0',{type:'redeal'});expect(f.s.history).toEqual(history);expect(f.s.round).toBe(2);expect(f.s.next).toBe(history[0].at(-1)!.player);assertCards(f.s);});
});

it('restored rooms give admin control to a returning guest when the prior host stays offline',()=>{const f=fixture();f.peek();f.s.players.forEach(p=>p.connected=false);connection(f.s,f.d,'p1',true);expect(f.s.host).toBe('p1');connection(f.s,f.d,'p0',true);expect(f.s.host).toBe('p1');});
it('explicit abort clears caller, timers, private interactions and previous results',()=>{const f=fixture();f.peek();f.draw();f.discard();f.settle();f.send('p1',{type:'call',window:f.s.window,turn:f.s.turn});f.send('p0',{type:'pause'});f.send('p0',{type:'abort'});const v=project(f.s,f.d,'p0');expect(v.phase).toBe('LOBBY');expect(v.caller).toBeUndefined();expect(v.finalTurns).toEqual([]);expect(v.history).toEqual([]);expect(v.effects).toEqual([]);expect(v.players.every(p=>p.slots.length===0&&!p.ready)).toBe(true);});

it('uses the exhausted-supply tie fallback without manufacturing any physical cards',()=>{const f=fixture(3);f.peek();const all=deck();const takeZero=()=>all.splice(all.findIndex(c=>c.value===0),1)[0];const zero=takeZero(),top=takeZero();f.s.players[0].slots=[{rev:1,card:zero}];f.s.players[1].slots=[];f.s.players[2].slots=[];for(const value of [...new Set(all.map(c=>c.value))]){const group=all.filter(c=>c.value===value);f.s.players[1].slots.push(...group.slice(0,group.length/2).map(card=>({rev:1,card})));f.s.players[2].slots.push(...group.slice(group.length/2).map(card=>({rev:1,card})));}f.s.deck=[];f.s.discard=[top];f.match('p0',[0]);expect(f.s.history[0].slice(1).every(r=>r.tie.includes('exhausted supply fallback'))).toBe(true);assertCards(f.s);});

it('repeats tied temporary scoring draws and returns those cards between passes',()=>{const f=fixture(3);f.peek();rig(f.s,[[0],[3],[3]],0,[2,2]);f.d.randomInt=()=>0;f.match('p0',[0]);expect(f.s.history[0][1].tie).toContain('→');expect(f.s.history[0][2].tie).toContain('→');expect(f.s.history[0].map(r=>r.place)).toEqual([1,2,3]);expect(f.s.history[0].slice(1).every(r=>r.sum===3&&r.count===1)).toBe(true);assertCards(f.s);});

it('protects a full second after a wrong-match reveal returns face down',()=>{const f=fixture();f.peek();rig(f.s,[[2,3],[4,5]],7,[8]);f.match('p0',[0]);const revealEnd=f.s.reveals[0].until;expect(f.s.unlockAt).toBeGreaterThanOrEqual(revealEnd+1000);f.setTime(revealEnd+999);tick(f.s,f.d);expect(()=>f.draw()).toThrow(/protected/);f.setTime(f.s.unlockAt);f.draw();expect(f.s.open).toBe(false);});

it('projects actual call eligibility and filters private movement faces per recipient',()=>{
 const f=fixture();f.peek();expect(project(f.s,f.d,'p1').canCallArchduke).toBe(false);rig(f.s,[[2,3],[4,5]],7,[9]);f.draw();
 const held=f.s.held!;expect(held.id).toBeTruthy();const mine=project(f.s,f.d,'p1'),other=project(f.s,f.d,'p0');
 expect(mine.movements.at(-1)?.value).toBe(9);expect(other.movements.at(-1)?.value).toBeUndefined();expect(other.held?.value).toBeUndefined();expect(JSON.stringify(other.movements)).not.toContain('privateTo');
 f.discard('p1',f.ref('p1',0));const [incoming,outgoing]=f.s.movements.slice(-2);expect(incoming.start).toBe(outgoing.start);expect(incoming.end).toBe(outgoing.end);
 expect(project(f.s,f.d,'p1').canCallArchduke).toBe(false);f.setTime(f.s.visualUntil);expect(project(f.s,f.d,'p1').canCallArchduke).toBe(true);expect(project(f.s,f.d,'p0').canCallArchduke).toBe(false);
 f.settle();f.draw('p0');expect(project(f.s,f.d,'p1').canCallArchduke).toBe(false);
});

 it('rejects every manual initial peek and preserves remaining automatic time on reconnect',()=>{const f=fixture();f.setTime(f.s.initialPeek!.revealAt);tick(f.s,f.d);f.advance(1360);const remaining=f.s.initialPeek!.hideAt-f.d.now();expect(()=>f.send('p0',{type:'peekInitial',target:f.ref(),reveal:true})).toThrow(/automatic/);connection(f.s,f.d,'p0',false);f.advance(5000);connection(f.s,f.d,'p0',true);expect(f.s.initialPeek!.hideAt-f.s.restartAt).toBe(remaining);f.setTime(f.s.initialPeek!.finishAt);tick(f.s,f.d);expect(f.s.phase).toBe('INTER_TURN');expect(()=>f.send('p0',{type:'peekInitial',target:f.ref(),reveal:true})).toThrow();});

describe('automatic final matching and individual results progression',()=>{
 function finalWindow(){const f=fixture();f.peek();rig(f.s,[[12,4],[6,8]],7,[9,12]);const caller=f.s.next;f.draw();f.discard();f.settle();f.send(caller,{type:'call',window:f.s.window,turn:f.s.turn});f.draw();f.discard();return f;}
 it('waits three full seconds after movement, rejects early finish and late matches, scores exactly once',()=>{
  const f=finalWindow();expect(f.s.finalEndsAt!-f.s.visualUntil).toBe(3000);f.settle();expect(()=>f.send('p1',{type:'finish',window:f.s.window})).toThrow();f.setTime(f.s.finalEndsAt!-1);expect(tick(f.s,f.d)).toBe(false);expect(f.s.history).toHaveLength(0);f.advance(1);expect(()=>f.match('p0',[0])).toThrow(/closed/);expect(tick(f.s,f.d)).toBe(true);expect(f.s.history).toHaveLength(1);expect(tick(f.s,f.d)).toBe(false);assertCards(f.s);
 });
 it('protects late matching movement and the full special-effect opportunity',()=>{
  const f=finalWindow();f.setTime(f.s.finalEndsAt!-100);f.match('p0',[0]);expect(f.s.effects[0].kind).toBe(12);expect(f.s.finalEndsAt).toBeUndefined();f.advance(6000);tick(f.s,f.d);expect(f.s.history).toHaveLength(0);f.send('p0',{type:'effect',effect:f.s.effects[0].id,targets:[f.ref('p0',1)]});f.setTime(f.s.effects[0].viewUntil!);tick(f.s,f.d);expect(f.s.finalEndsAt).toBe(f.d.now()+3000);f.setTime(f.s.finalEndsAt!);tick(f.s,f.d);expect(f.s.history).toHaveLength(1);
 });
 it('freezes the countdown while paused and preserves the remaining time on resume',()=>{
  const f=finalWindow();f.settle();const remaining=f.s.finalEndsAt!-f.d.now();f.send('p0',{type:'pause'});f.advance(10000);expect(tick(f.s,f.d)).toBe(false);f.send('p0',{type:'resume'});expect(f.s.finalEndsAt!-f.s.restartAt).toBe(remaining);f.setTime(f.s.finalEndsAt!);tick(f.s,f.d);expect(f.s.history).toHaveLength(1);
 });
 it('lets each player review results before readiness, with only the host allowed to deal',()=>{
  const f=finalWindow();f.setTime(f.s.finalEndsAt!);tick(f.s,f.d);const history=structuredClone(f.s.history);f.send('p1',{type:'next'});expect(f.s.phase).toBe('LOBBY');expect(f.s.players.every(p=>p.slots.length===0&&!p.ready)).toBe(true);expect(f.s.players[0].reviewingResults).toBe(true);expect(f.s.players[1].reviewingResults).toBe(false);expect(()=>f.send('p0',{type:'ready',ready:true})).toThrow();f.send('p1',{type:'ready',ready:true});f.send('p0',{type:'next'});f.send('p0',{type:'ready',ready:true});expect(()=>f.send('p1',{type:'start'})).toThrow(/host/);f.send('p0',{type:'start'});expect(f.s.round).toBe(2);expect(f.s.history).toEqual(history);expect(f.s.players.every(p=>p.slots.length===4)).toBe(true);assertCards(f.s);
 });
});

it('publishes one cosmetic call event without changing matching or movement eligibility',()=>{
 const f=fixture();f.peek();f.draw();const actor=f.s.held!.owner;f.discard();f.settle();const before={unlock:f.s.unlockAt,visual:f.s.visualUntil,window:f.s.window,turn:f.s.turn};f.send(actor,{type:'call',window:f.s.window,turn:f.s.turn});expect({unlock:f.s.unlockAt,visual:f.s.visualUntil,window:f.s.window,turn:f.s.turn}).toEqual(before);const call=project(f.s,f.d,'p0').movements.find(m=>m.kind==='call')!;expect(call.end-call.start).toBe(1400);expect(call.value).toBeUndefined();expect(()=>f.send(actor,{type:'call',window:f.s.window,turn:f.s.turn})).toThrow();expect(f.s.movements.filter(m=>m.kind==='call')).toHaveLength(1);
});

describe('per-card matching penalties',()=>{
 for(const count of [1,2,3])for(const late of [false,true])it(`${count} distinct ${late?'late':'wrong'} cards each incur one hidden penalty`,()=>{
  const f=fixture();f.peek();rig(f.s,[[2,3,4],[5,6]],7,[8,9,10,6]);if(late)f.draw();const reply=f.match('p0',Array.from({length:count},(_,i)=>i));expect(reply.results).toEqual(Array(count).fill(late?'late':'wrong'));expect(f.s.players[0].slots).toHaveLength(3+count);expect(f.s.players[0].slots.slice(0,3).map(s=>s.card?.value)).toEqual([2,3,4]);
  for(const viewer of ['p0','p1']){const v=project(f.s,f.d,viewer);expect(v.players[0].slots.slice(3).every(s=>s.value===undefined)).toBe(true);expect(v.movements.filter(m=>m.kind==='penalty').every(m=>m.value===undefined)).toBe(true);}f.match('p0',[0]);expect(f.s.players[0].slots).toHaveLength(4+count);assertCards(f.s);
 });
 it('ordinary and invalid final matches never extend the deadline',()=>{for(const wrong of [false,true]){const f=fixture();f.peek();rig(f.s,[[7,3],[4,5]],7);f.s.caller='p1';f.s.finalTurns=[];f.s.phase='FINAL_MATCH_WINDOW';f.s.finalEndsAt=f.d.now()+3000;const end=f.s.finalEndsAt;f.advance(2900);f.match('p0',[wrong?1:0]);expect(f.s.finalEndsAt).toBe(end);f.setTime(end);tick(f.s,f.d);expect(f.s.phase).toBe('ROUND_RESULTS');}});
 it('final match to zero scores immediately without waiting for the deadline',()=>{const f=fixture();f.peek();rig(f.s,[[7],[4,5]],7);f.s.caller='p1';f.s.phase='FINAL_MATCH_WINDOW';f.s.finalEndsAt=f.d.now()+3000;f.match('p0',[0]);expect(f.s.phase).toBe('ROUND_RESULTS');expect(f.s.history).toHaveLength(1);});
});

it('mixed batch removes correct cards and appends a penalty for each wrong card',()=>{const f=fixture();f.peek();rig(f.s,[[7,2,7,3],[4,5]],7,[8,9]);expect(f.match('p0',[0,1,2,3]).results).toEqual(['matched','wrong','matched','wrong']);expect(f.s.players[0].slots.map(s=>s.card?.value)).toEqual([undefined,2,undefined,3,8,9]);expect(f.s.movements.filter(m=>m.kind==='penalty')).toHaveLength(2);assertCards(f.s);});

describe('balanced rows and stable target identities',()=>{
 const positions=(s:State,id='p0')=>project(s, {now:()=>0} as Dependencies,id).players.find(p=>p.id===id)!.slots.filter(s=>s.occupied).map(s=>[s.index,s.row,s.column]);
 it('four cards plus two penalties is 3/3 and batches reevaluate the shorter row',()=>{const f=fixture();f.peek();rig(f.s,[[2,3,4,5],[6,8]],7,[9,10]);f.match('p0',[0,1]);expect(positions(f.s)).toEqual([[0,0,0],[1,1,0],[2,0,1],[3,1,1],[4,0,2],[5,1,2]]);expect(f.s.players[0].columns).toBe(3);});
 it('a middle match slides only its row, old references cannot target the sliding neighbor',()=>{const f=fixture();f.peek();rig(f.s,[[2,3,7,5,6,8],[4,9]],7);const stale=f.ref('p0',2),neighbor=f.ref('p0',4),identity=f.s.players[0].slots[4].card!.id;f.match('p0',[2]);expect(positions(f.s)).toEqual([[0,0,0],[1,1,0],[3,1,1],[4,0,1],[5,1,2]]);expect(f.s.players[0].slots[4].card!.id).toBe(identity);expect(()=>f.send('p0',{type:'match',window:f.s.window,slots:[stale]})).toThrow(/changed/);expect(f.s.players[0].slots[4].rev).toBe(neighbor.rev);f.match('p0',[0,1]);const added=f.s.players[0].slots.slice(6);expect(added.map(s=>s.row)).toEqual([0,0]);expect(positions(f.s).filter(x=>x[1]===0)).toHaveLength(4);expect(positions(f.s).filter(x=>x[1]===1)).toHaveLength(3);assertCards(f.s);});
 it('Give uses the same shorter-row policy after matching gaps close',()=>{const f=fixture();f.peek();rig(f.s,[[1,1,3],[1,5,1,7]],1,[8,9]);f.match('p1',[0,2]);f.match('p0',[0,1]);f.settle();while(f.s.effects.length){const e=f.s.effects[0];f.send(e.actor,{type:'effect',effect:e.id,recipient:e.actor==='p0'?'p1':'p0'});f.settle();}expect(f.s.players[1].slots.slice(4).map(s=>s.row)).toEqual([0,0]);expect(positions(f.s,'p1').filter(x=>x[1]===0)).toHaveLength(2);expect(positions(f.s,'p1').filter(x=>x[1]===1)).toHaveLength(2);});
});
