import { afterEach, describe, expect, it } from 'vitest';
import { io, type Socket } from 'socket.io-client';
import { mkdtempSync, rmSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { AddressInfo } from 'node:net';
import { createApp } from '../src/server/app.js';
import { config } from '../src/server/config.js';
import { MemoryStore, SQLiteStore } from '../src/server/store.js';
import type { View, Reply } from '../src/shared/protocol.js';
import { assertCards } from '../src/engine/model.js';
const origin='http://localhost:3000';
const cfg=()=>config({HOST_SECRET:'integration-only-passphrase',PUBLIC_ORIGIN:origin,PORT:'0'});
const running:ReturnType<typeof createApp>[]=[];const sockets:Socket[]=[];const dirs:string[]=[];
afterEach(async()=>{sockets.splice(0).forEach(s=>s.disconnect());for(const s of running.splice(0))await s.close();for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true});});
async function server(store?:MemoryStore|SQLiteStore){const s=createApp(cfg(),store);running.push(s);await new Promise<void>((r,j)=>{s.http.once('error',j);s.http.listen(0,'127.0.0.1',r);});return {...s,url:`http://127.0.0.1:${(s.http.address() as AddressInfo).port}`};}
async function post(url:string,path:string,body:unknown,cookie=''){const response=await fetch(url+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({...body as object,id:crypto.randomUUID()})});const json=await response.json();return {status:response.status,json,cookie:response.headers.get('set-cookie')?.split(';')[0]??cookie};}
async function seat(url:string,room:string,cookie:string){const socket=io(url,{transports:['websocket'],auth:{room},extraHeaders:{Origin:origin,Cookie:cookie},autoConnect:false,reconnection:false});sockets.push(socket);let view:View;socket.on('state',v=>view=v);await new Promise<void>((resolve,reject)=>{socket.once('state',()=>resolve());socket.once('connect_error',reject);socket.connect();});return {socket,get v(){return view!;},send:async(action:object,id=crypto.randomUUID()):Promise<Reply>=>await socket.timeout(4000).emitWithAck('command',{id,game:view!.game,round:view!.round,...action})};}
async function waitFor(predicate:()=>boolean){const until=Date.now()+5000;while(!predicate()){if(Date.now()>until)throw new Error('Condition timed out');await new Promise(r=>setTimeout(r,10));}}
async function game(s:Awaited<ReturnType<typeof server>>,count=2){const creator=await post(s.url,'/api/create',{name:'Host',secret:cfg().secret});const room=creator.json.room as string;const a=await seat(s.url,room,creator.cookie);const seats=[a];const cookies=[creator.cookie];for(let i=1;i<count;i++){const joined=await post(s.url,'/api/join',{name:`Guest ${i}`,invite:a.v.invite});cookies.push(joined.cookie);seats.push(await seat(s.url,room,joined.cookie));}await waitFor(()=>a.v.players.length===count);return {room,seats,cookies};}
async function start(g:Awaited<ReturnType<typeof game>>){for(const p of g.seats)expect((await p.send({type:'ready',ready:true})).ok).toBe(true);expect((await g.seats[0].send({type:'start'})).ok).toBe(true);for(const p of g.seats){await waitFor(()=>p.v.phase==='INITIAL_PEEK');await new Promise(r=>setTimeout(r,Math.max(0,p.v.visualUntil-Date.now()+5)));const me=p.v.players.find(q=>q.id===p.v.you)!;expect((await p.send({type:'peekInitial',slots:me.slots.slice(0,2).map(x=>({player:me.id,slot:x.index,rev:x.rev}))})).ok).toBe(true);expect((await p.send({type:'hideInitial'})).ok).toBe(true);}await waitFor(()=>g.seats.every(p=>p.v.open));}

describe('real HTTP and websocket boundary',()=>{
 it('requires host secret and origin, rejects invalid invites, isolates rooms and caps at ten',async()=>{const s=await server();expect((await post(s.url,'/api/create',{name:'Host',secret:'wrong'})).status).toBe(403);expect((await post(s.url,'/api/join',{name:'Guest',invite:'unknown'})).status).toBe(404);expect((await fetch(s.url+'/api/create',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status).toBe(403);const g=await game(s,10);expect((await post(s.url,'/api/join',{name:'Extra',invite:g.seats[0].v.invite})).status).toBe(400);const other=await game(s,2);expect(other.seats[0].v.room).not.toBe(g.room);expect((await fetch(s.url+`/api/room/${other.room}`,{headers:{Cookie:g.cookies[0]}})).status).toBe(403);expect((await fetch(s.url+`/api/room/${other.room}`,{headers:{Cookie:g.cookies[0].replace(`ad_${g.room}=`,`ad_${other.room}=`)}})).status).toBe(403);await start(g);expect(g.seats).toHaveLength(10);for(const p of g.seats)expect(p.v.players.flatMap(q=>q.slots).every(x=>x.value===undefined)).toBe(true);const samples=s.rooms.metrics.slice().sort((a,b)=>a-b);mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/transport-metrics.json',JSON.stringify({clients:10,samples:samples.length,p95ms:samples[Math.floor(samples.length*.95)],maxMs:samples.at(-1),runtime:process.version,platform:process.platform,arch:process.arch},null,2));console.log(`10-client queue + commit + fan-out p95: ${samples[Math.floor(samples.length*.95)].toFixed(2)} ms (${samples.length} transitions)`);});
 it('rejects actor forgery and obsolete scopes, deduplicates sent actions and reports status',async()=>{const s=await server();const g=await game(s);await start(g);const a=g.seats[0];const target={player:a.v.you,slot:0,rev:1};const id=crypto.randomUUID();const response=await a.send({type:'match',window:a.v.window,slots:[target]},id);expect(response.ok).toBe(true);const seq=a.v.seq;expect(await a.send({type:'match',window:a.v.window,slots:[target]},id)).toEqual(response);expect(a.v.seq).toBe(seq);expect(await a.socket.emitWithAck('actionStatus',id)).toEqual(response);expect((await a.send({type:'match',window:a.v.window,slots:[target],actor:g.seats[1].v.you})).code).toBe('MALFORMED');expect((await a.send({type:'match',round:99,window:a.v.window,slots:[target]})).code).toBe('STALE');assertCards(s.rooms.rooms.get(g.room)!.data.state);});
 it('takes over a seat without duplicating it or pausing, then refresh pauses and resumes explicitly',async()=>{const s=await server();const g=await game(s);await start(g);const old=g.seats[0];const replacement=await seat(s.url,g.room,g.cookies[0]);await waitFor(()=>!old.socket.connected);expect(replacement.v.players).toHaveLength(2);expect(replacement.v.you).toBe(old.v.you);expect(replacement.v.paused).toBeUndefined();replacement.socket.disconnect();await waitFor(()=>!!g.seats[1].v.paused);const reconnect=await seat(s.url,g.room,g.cookies[0]);expect(reconnect.v.paused).toBeDefined();expect(reconnect.v.players.flatMap(p=>p.slots).every(x=>x.value===undefined)).toBe(true);const host=g.seats[1];expect((await host.send({type:'resume'})).ok).toBe(true);expect(host.v.restartAt).toBeGreaterThan(host.v.serverNow);});
 it('persists state and deduplication before ack and restores paused state in SQLite',async()=>{const dir=mkdtempSync(join(tmpdir(),'archduke-sqlite-'));dirs.push(dir);const s=await server(new SQLiteStore(dir));const g=await game(s);await start(g);const a=g.seats[0];const id=crypto.randomUUID();const action={type:'match',window:a.v.window,slots:[{player:a.v.you,slot:0,rev:1}]};const reply=await a.send(action,id);const saved=structuredClone(s.rooms.rooms.get(g.room)!.data.state);await s.close();// Remove underlying server by HTTP identity.
 const ix=running.findIndex(x=>x.http===s.http);if(ix>=0)running.splice(ix,1);
 const restarted=await server(new SQLiteStore(dir));const room=restarted.rooms.rooms.get(g.room)!;expect(room.data.state.paused).toBeDefined();expect(room.data.state.players.map(p=>p.slots)).toEqual(saved.players.map(p=>p.slots));expect(room.data.state.effects).toMatchObject(saved.effects.map(e=>({id:e.id,actor:e.actor,kind:e.kind})));const rejoined=await seat(restarted.url,g.room,g.cookies[0]);expect(await rejoined.send(action,id)).toEqual(reply);expect(rejoined.v.you).toBe(a.v.you);assertCards(room.data.state);});
 it('does not acknowledge or publish a failed persistence commit',async()=>{class FailingStore extends MemoryStore{fail=false;override save(){if(this.fail)throw new Error('disk failed');}}const store=new FailingStore();const s=await server(store);const g=await game(s);await start(g);const a=g.seats[0];const before=structuredClone(s.rooms.rooms.get(g.room)!.data.state);store.fail=true;const reply=await a.send({type:'match',window:a.v.window,slots:[{player:a.v.you,slot:0,rev:1}]});expect(reply.code).toBe('PERSISTENCE');expect(s.rooms.rooms.get(g.room)!.data.state).toEqual(before);store.fail=false;});
 it('shows memory room loss after process replacement',async()=>{const s=await server();const g=await game(s);const replacement=await server();const r=await fetch(replacement.url+`/api/room/${g.room}`,{headers:{Cookie:g.cookies[0]}});expect(r.status).toBe(404);expect((await r.json()).message).toBe('This game is no longer available');});
 it('jittered concurrent actions converge without replaying offline commands',async()=>{const s=await server();const g=await game(s,6);await start(g);const started=Date.now();const timings:{seat:number;injectedDelayMs:number;ackElapsedMs:number;seq:number}[]=[];const replies=await Promise.all(g.seats.map(async(p,i)=>{const injectedDelayMs=[35,0,22,9,48,16][i];await new Promise(r=>setTimeout(r,injectedDelayMs));const reply=await p.send({type:'match',window:p.v.window,slots:[{player:p.v.you,slot:0,rev:1}]});timings.push({seat:i,injectedDelayMs,ackElapsedMs:Date.now()-started,seq:reply.seq});return reply;}));mkdirSync('artifacts',{recursive:true});writeFileSync('artifacts/jitter-metrics.json',JSON.stringify(timings.sort((a,b)=>a.seq-b.seq),null,2));expect(replies.every(r=>r.ok)).toBe(true);const seq=s.rooms.rooms.get(g.room)!.data.state.seq;await waitFor(()=>g.seats.every(p=>p.v.seq===seq));const publicStates=g.seats.map(p=>({...p.v,you:'',acks:{}}));expect(publicStates.every(p=>JSON.stringify(p.players)===JSON.stringify(publicStates[0].players))).toBe(true);assertCards(s.rooms.rooms.get(g.room)!.data.state);});
});

describe('configuration',()=>{it('rejects missing credentials and unsafe production timing/origin',()=>{expect(()=>config({})).toThrow(/HOST_SECRET/);for(const delay of ['0','-1','NaN',''])expect(()=>config({HOST_SECRET:'test-passphrase',MATCH_DELAY_MS:delay})).toThrow(/MATCH_DELAY/);expect(()=>config({HOST_SECRET:'test-passphrase',NODE_ENV:'production',PUBLIC_ORIGIN:origin})).toThrow(/HTTPS/);});});

describe('admission retries, expiration, and fail-closed lifecycle',()=>{
 it('deduplicates create and join even when the initial HTTP response/cookie was lost',async()=>{const s=await server();const createId=crypto.randomUUID();const request=async(path:string,body:object)=>{const r=await fetch(s.url+path,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});expect(r.status).toBe(200);return {body:await r.json(),cookie:r.headers.get('set-cookie')!.split(';')[0]};};const first=await request('/api/create',{id:createId,name:'Host',secret:cfg().secret});const retry=await request('/api/create',{id:createId,name:'Host',secret:cfg().secret});expect(retry.body.room).toBe(first.body.room);expect(s.rooms.rooms.size).toBe(1);const host=await seat(s.url,retry.body.room,retry.cookie);const joinId=crypto.randomUUID();await request('/api/join',{id:joinId,name:'Guest',invite:host.v.invite});const joined=await request('/api/join',{id:joinId,name:'Guest',invite:host.v.invite});await seat(s.url,joined.body.room,joined.cookie);expect(s.rooms.rooms.get(joined.body.room)!.data.state.players).toHaveLength(2);});
 it('expires abandoned and completed rooms and rejects zombie connections',async()=>{const s=await server();const g=await game(s);const room=s.rooms.rooms.get(g.room)!;room.data.state.phase='GAME_RESULTS';room.data.lastActive=s.rooms.deps.now()-1800001;await s.rooms.timers();expect(s.rooms.rooms.has(g.room)).toBe(false);await waitFor(()=>g.seats.every(p=>!p.socket.connected));expect((await fetch(s.url+`/api/room/${g.room}`,{headers:{Cookie:g.cookies[0]}})).status).toBe(404);});
 it('retries a failed disconnect commit and blocks new gameplay until it is durable',async()=>{class FailingStore extends MemoryStore{fail=false;override save(){if(this.fail)throw new Error('disk unavailable');}}const store=new FailingStore();const s=await server(store);const g=await game(s);await start(g);store.fail=true;g.seats[1].socket.disconnect();await waitFor(()=>s.rooms.rooms.get(g.room)!.pendingDisconnects.size===1);const reply=await g.seats[0].send({type:'match',window:g.seats[0].v.window,slots:[{player:g.seats[0].v.you,slot:0,rev:1}]});expect(reply.ok).toBe(false);store.fail=false;await s.rooms.timers();expect(s.rooms.rooms.get(g.room)!.pendingDisconnects.size).toBe(0);expect(s.rooms.rooms.get(g.room)!.data.state.paused).toBeDefined();});
});

it('SQLite recovery preserves a depleted-supply pause and its explicit redeal path',async()=>{const dir=mkdtempSync(join(tmpdir(),'archduke-depleted-'));dirs.push(dir);const first=await server(new SQLiteStore(dir));const g=await game(first);await start(g);const room=first.rooms.rooms.get(g.room)!;await first.rooms.transaction(room,data=>{data.state.paused={reason:'No cards available',since:first.rooms.deps.now(),graceUntil:first.rooms.deps.now()+60000};data.state.open=false;});await first.close();running.splice(running.findIndex(s=>s.http===first.http),1);const restored=await server(new SQLiteStore(dir));expect(restored.rooms.rooms.get(g.room)!.data.state.paused?.reason).toBe('No cards available');const a=await seat(restored.url,g.room,g.cookies[0]);await seat(restored.url,g.room,g.cookies[1]);expect((await a.send({type:'resume'})).ok).toBe(false);expect((await a.send({type:'redeal'})).ok).toBe(true);expect(a.v.phase).toBe('INITIAL_PEEK');expect(a.v.round).toBe(1);});
